################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 3.2
##  \   \         Application : 7 Series FPGAs Transceivers Wizard
##  /   /         Filename : gt6_rtm34l.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## USER CONSTRAINTS FILE FOR MGT WRAPPER EXAMPLE DESIGN
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard
##
## Device:  xc7vx690t
## Package: ffg1927
##
## (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
## 
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES.

 

################################## Clock Constraints ##########################


#create_clock -period 20.0 [get_ports SYSCLK_IN]

# User Clock Constraints
create_clock -period 6.667 [get_pins -hier -filter {name=~*gt0_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt0_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt0_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt0_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt0_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt1_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt1_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt1_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt1_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt1_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt2_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt2_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt2_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt2_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt2_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt3_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt3_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt3_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt3_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt3_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt4_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt4_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt4_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt4_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt4_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt5_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt5_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt5_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt5_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt5_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt6_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt6_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt6_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt6_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt6_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt7_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt7_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt7_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt7_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt7_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt8_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt8_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt8_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt8_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt8_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt9_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt9_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt9_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt9_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt9_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt10_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt10_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt10_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt10_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt10_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt11_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt11_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt11_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt11_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt11_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt12_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt12_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt12_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt12_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt12_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt13_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt13_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt13_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt13_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt13_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt14_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt14_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt14_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt14_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt14_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt15_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt15_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt15_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt15_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt15_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt16_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt16_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt16_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt16_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt16_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt17_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt17_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt17_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt17_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt17_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt18_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt18_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt18_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt18_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt18_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt19_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt19_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt19_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt19_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt19_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt20_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt20_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt20_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt20_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt20_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt21_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt21_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt21_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt21_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt21_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt22_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt22_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt22_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt22_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt22_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt23_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt23_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt23_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt23_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt23_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt24_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt24_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt24_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt24_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt24_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt25_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt25_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt25_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt25_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt25_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt26_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt26_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt26_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt26_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt26_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt27_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt27_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt27_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt27_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt27_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt28_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt28_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt28_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt28_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt28_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt29_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt29_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt29_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt29_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt29_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt30_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt30_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt30_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt30_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt30_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt31_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt31_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt31_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt31_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt31_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt32_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt32_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt32_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt32_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt32_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]



create_clock -period 6.667 [get_pins -hier -filter {name=~*gt33_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt33_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt33_gt6_rtm34l_i*gthe2_i*TXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]

#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]] -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt33_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt33_gt6_rtm34l_i*gthe2_i*RXOUTCLK}]] -to [get_clocks -include_generated_clocks -of_objects [get_ports SYSCLK_IN]]




####################### GT reference clock constraints #########################
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt0_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt1_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt2_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt3_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt4_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt5_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt6_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt7_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt8_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt9_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt10_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt11_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt12_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt13_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt14_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt15_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt16_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt17_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt18_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt19_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt20_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt21_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt22_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt23_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt24_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt25_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt26_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt27_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt28_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt29_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt30_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt31_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt32_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt33_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt0_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt1_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt2_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt3_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt4_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt5_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt6_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt7_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt8_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt9_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt10_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt11_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt12_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt13_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt14_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt15_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt16_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt17_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt18_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt19_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt20_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt21_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt22_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt23_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt24_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt25_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt26_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt27_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt28_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt29_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt30_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt31_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt32_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt33_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt0_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt1_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt2_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt3_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt4_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt5_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt6_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt7_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt8_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt9_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt10_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt11_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt12_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt13_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt14_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt15_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt16_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt17_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt18_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt19_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt20_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt21_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt22_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt23_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt24_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt25_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt26_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt27_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt28_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt29_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt30_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt31_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt32_gtrefclk0_in}]
create_clock -period 6.667 [get_nets -hier -filter {name=~*gt33_gtrefclk0_in}]

################################# RefClk Location constraints (Can be uncommented) ##################### 
## set_property LOC AR36 [get_ports  Q1_CLK0_GTREFCLK_PAD_N_IN ] 
## set_property LOC AR35 [get_ports  Q1_CLK0_GTREFCLK_PAD_P_IN ]
## set_property LOC AA36 [get_ports  Q4_CLK0_GTREFCLK_PAD_N_IN ] 
## set_property LOC AA35 [get_ports  Q4_CLK0_GTREFCLK_PAD_P_IN ]
## set_property LOC J36 [get_ports  Q7_CLK0_GTREFCLK_PAD_N_IN ] 
## set_property LOC J35 [get_ports  Q7_CLK0_GTREFCLK_PAD_P_IN ]


