################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 3.3
##  \   \         Application : 7 Series FPGAs Transceivers Wizard
##  /   /         Filename : gt64_rtm34l_exdes.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## USER CONSTRAINTS FILE FOR MGT WRAPPER EXAMPLE DESIGN
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard
##
## Device:  xc7vx690t
## Package: ffg1927
##
## (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
## 
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES.


################################## Clock Constraints ##########################


####################### GT reference clock constraints #########################
 

    create_clock -period 5.0 [get_ports Q1_CLK0_GTREFCLK_PAD_P_IN]
 

    create_clock -period 5.0 [get_ports Q4_CLK0_GTREFCLK_PAD_P_IN]
 

    create_clock -period 5.0 [get_ports Q7_CLK0_GTREFCLK_PAD_P_IN]


#create_clock -name GT0_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt0_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT1_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt1_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT2_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt2_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT3_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt3_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT4_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt4_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT5_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt5_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT6_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt6_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT7_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt7_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT8_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt8_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT9_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt9_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT10_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt10_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT11_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt11_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT12_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt12_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT13_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt13_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT14_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt14_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT15_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt15_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT16_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt16_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT17_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt17_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT18_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt18_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT19_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt19_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT20_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt20_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT21_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt21_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT22_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt22_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT23_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt23_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT24_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt24_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT25_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt25_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT26_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt26_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT27_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt27_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT28_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt28_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT29_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt29_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT30_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt30_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT31_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt31_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT32_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt32_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT33_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt33_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]

#create_clock -name GT0_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt0_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT1_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt1_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT2_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt2_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT3_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt3_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT4_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt4_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT5_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt5_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT6_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt6_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT7_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt7_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT8_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt8_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT9_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt9_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT10_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt10_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT11_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt11_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT12_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt12_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT13_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt13_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT14_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt14_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT15_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt15_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT16_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt16_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT17_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt17_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT18_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt18_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT19_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt19_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT20_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt20_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT21_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt21_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT22_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt22_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT23_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt23_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT24_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt24_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT25_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt25_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT26_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt26_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT27_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt27_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT28_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt28_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT29_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt29_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT30_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt30_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT31_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt31_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT32_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt32_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT33_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt33_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]

#create_clock -name GT0_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt0_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT1_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt1_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT2_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt2_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT3_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt3_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT4_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt4_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT5_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt5_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT6_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt6_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT7_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt7_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT8_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt8_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT9_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt9_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT10_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt10_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT11_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt11_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT12_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt12_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT13_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt13_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT14_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt14_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT15_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt15_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT16_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt16_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT17_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt17_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT18_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt18_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT19_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt19_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT20_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt20_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT21_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt21_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT22_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt22_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT23_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt23_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT24_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt24_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT25_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt25_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT26_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt26_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT27_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt27_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT28_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt28_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT29_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt29_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT30_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt30_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT31_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt31_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT32_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt32_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]
#create_clock -name GT33_GTREFCLK0_IN -period 5.0 [get_pins -hier -filter {name=~*gt33_gt64_rtm34l_i*gthe2_i*GTREFCLK0}]


#create_clock -name drpclk_in_i -period 20.0 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt_usrclk_source*DRP_CLK_BUFG*I}]

create_clock -name drpclk_in_i -period 20.0 [get_ports DRP_CLK_IN_P]

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt0_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt0_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt1_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt1_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt2_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt2_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt3_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt3_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt4_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt4_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt5_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt5_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt6_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt6_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt7_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt7_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt8_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt8_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt9_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt9_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt10_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt10_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt11_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt11_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt12_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt12_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt13_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt13_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt14_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt14_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt15_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt15_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt16_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt16_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt17_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt17_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt18_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt18_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt19_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt19_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt20_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt20_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt21_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt21_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt22_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt22_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt23_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt23_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt24_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt24_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt25_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt25_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt26_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt26_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt27_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt27_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt28_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt28_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt29_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt29_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt30_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt30_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt31_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt31_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt32_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt32_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

#set_false_path -from drpclk_in_i -to [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt33_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]]
#set_false_path -from [get_clocks -include_generated_clocks -of_objects [get_pins -hier -filter {name=~*gt33_gt64_rtm34l_i*gthe2_i*TXOUTCLK}]] -to drpclk_in_i

# User Clock Constraints
create_clock -name gt0_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt0_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt0_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt0_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt1_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt1_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt1_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt1_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt2_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt2_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt2_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt2_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt3_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt3_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt3_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt3_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt4_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt4_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt4_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt4_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt5_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt5_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt5_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt5_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt6_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt6_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt6_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt6_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt7_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt7_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt7_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt7_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt8_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt8_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt8_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt8_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt9_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt9_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt9_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt9_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt10_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt10_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt10_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt10_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt11_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt11_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt11_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt11_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt12_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt12_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt12_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt12_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt13_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt13_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt13_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt13_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt14_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt14_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt14_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt14_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt15_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt15_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt15_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt15_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt16_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt16_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt16_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt16_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt17_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt17_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt17_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt17_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt18_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt18_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt18_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt18_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt19_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt19_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt19_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt19_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt20_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt20_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt20_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt20_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt21_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt21_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt21_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt21_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt22_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt22_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt22_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt22_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt23_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt23_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt23_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt23_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt24_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt24_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt24_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt24_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt25_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt25_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt25_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt25_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt26_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt26_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt26_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt26_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt27_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt27_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt27_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt27_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt28_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt28_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt28_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt28_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt29_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt29_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt29_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt29_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt30_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt30_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt30_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt30_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt31_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt31_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt31_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt31_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt32_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt32_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt32_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt32_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]

create_clock -name gt33_txusrclk_i -period 6.25 [get_pins -hier -filter {name=~*gt64_rtm34l_support_i*gt64_rtm34l_init_i/gt33_txoutclk_out}]
#set_false_path -from [get_clocks -include_generated_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt33_txusrclk_i"]
#set_false_path -from [get_clocks -include_generated_clocks "gt33_txusrclk_i"] -to [get_clocks -include_generated_clocks "drpclk_in_i"]


set_false_path -to [get_pins -hierarchical -filter {NAME =~ *_txfsmresetdone_r*/CLR}]

################################# RefClk Location constraints #####################
set_property LOC AR36 [get_ports  Q1_CLK0_GTREFCLK_PAD_N_IN ] 
set_property LOC AR35 [get_ports  Q1_CLK0_GTREFCLK_PAD_P_IN ]
set_property LOC AA36 [get_ports  Q4_CLK0_GTREFCLK_PAD_N_IN ] 
set_property LOC AA35 [get_ports  Q4_CLK0_GTREFCLK_PAD_P_IN ]
set_property LOC J36 [get_ports  Q7_CLK0_GTREFCLK_PAD_N_IN ] 
set_property LOC J35 [get_ports  Q7_CLK0_GTREFCLK_PAD_P_IN ]

## LOC constrain for DRP_CLK_P/N 
## set_property LOC C25 [get_ports  DRP_CLK_IN_P]
## set_property LOC B25 [get_ports  DRP_CLK_IN_N]
 
################################# mgt wrapper constraints #####################

##---------- Set placement for gt0_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y0 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt0_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt1_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y1 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt1_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt2_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y2 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt2_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt3_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y3 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt3_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt4_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y4 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt4_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt5_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y5 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt5_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt6_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y6 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt6_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt7_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y7 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt7_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt8_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y8 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt8_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt9_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y9 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt9_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt10_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y10 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt10_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt11_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y11 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt11_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt12_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y12 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt12_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt13_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y13 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt13_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt14_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y14 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt14_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt15_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y15 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt15_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt16_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y16 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt16_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt17_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y17 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt17_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt18_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y18 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt18_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt19_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y19 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt19_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt20_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y20 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt20_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt21_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y21 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt21_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt22_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y22 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt22_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt23_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y23 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt23_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt24_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y24 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt24_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt25_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y25 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt25_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt26_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y26 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt26_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt27_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y27 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt27_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt28_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y28 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt28_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt29_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y29 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt29_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt30_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y30 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt30_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt31_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y31 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt31_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt32_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y32 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt32_gt64_rtm34l_i/gthe2_i]
##---------- Set placement for gt33_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X0Y33 [get_cells gt64_rtm34l_support_i/gt64_rtm34l_init_i/U0/gt64_rtm34l_i/gt33_gt64_rtm34l_i/gthe2_i]

##---------- Set ASYNC_REG for flop which have async input ----------
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt0_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt0_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt1_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt1_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt2_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt2_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt3_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt3_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt4_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt4_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt5_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt5_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt6_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt6_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt7_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt7_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt8_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt8_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt9_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt9_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt10_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt10_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt11_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt11_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt12_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt12_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt13_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt13_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt14_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt14_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt15_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt15_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt16_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt16_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt17_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt17_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt18_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt18_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt19_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt19_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt20_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt20_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt21_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt21_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt22_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt22_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt23_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt23_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt24_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt24_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt25_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt25_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt26_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt26_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt27_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt27_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt28_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt28_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt29_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt29_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt30_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt30_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt31_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt31_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt32_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt32_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt33_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt33_frame_check*system_reset_r_reg}]

##---------- Set False Path from one clock to other ----------
