## UCF output
set_property PACKAGE_PIN AH26 [get_ports FB1_RX_LVDS_P[0] ]
set_property PACKAGE_PIN AH27 [get_ports FB1_RX_LVDS_N[0] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[0] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[0] ]
set_property PACKAGE_PIN AG25 [get_ports FB1_RX_LVDS_P[1] ]
set_property PACKAGE_PIN AH25 [get_ports FB1_RX_LVDS_N[1] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[1] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[1] ]
set_property PACKAGE_PIN AF26 [get_ports FB1_RX_LVDS_P[2] ]
set_property PACKAGE_PIN AF27 [get_ports FB1_RX_LVDS_N[2] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[2] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[2] ]
set_property PACKAGE_PIN AD27 [get_ports FB1_RX_LVDS_P[3] ]
set_property PACKAGE_PIN AD28 [get_ports FB1_RX_LVDS_N[3] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[3] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[3] ]
set_property PACKAGE_PIN AE28 [get_ports FB1_RX_LVDS_P[4] ]
set_property PACKAGE_PIN AF28 [get_ports FB1_RX_LVDS_N[4] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[4] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[4] ]
set_property PACKAGE_PIN AD29 [get_ports FB1_RX_LVDS_P[5] ]
set_property PACKAGE_PIN AE29 [get_ports FB1_RX_LVDS_N[5] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[5] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[5] ]
set_property PACKAGE_PIN AC29 [get_ports FB1_RX_LVDS_P[6] ]
set_property PACKAGE_PIN AC30 [get_ports FB1_RX_LVDS_N[6] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[6] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[6] ]
set_property PACKAGE_PIN AB24 [get_ports FB1_RX_LVDS_P[7] ]
set_property PACKAGE_PIN AC25 [get_ports FB1_RX_LVDS_N[7] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[7] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[7] ]
set_property PACKAGE_PIN AG22 [get_ports FB1_RX_LVDS_P[8] ]
set_property PACKAGE_PIN AH22 [get_ports FB1_RX_LVDS_N[8] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[8] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[8] ]
set_property PACKAGE_PIN AE23 [get_ports FB1_RX_LVDS_P[9] ]
set_property PACKAGE_PIN AF23 [get_ports FB1_RX_LVDS_N[9] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[9] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[9] ]
set_property PACKAGE_PIN AJ27 [get_ports FB1_RX_LVDS_P[10] ]
set_property PACKAGE_PIN AK28 [get_ports FB1_RX_LVDS_N[10] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[10] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[10] ]
set_property PACKAGE_PIN AG30 [get_ports FB1_RX_LVDS_P[11] ]
set_property PACKAGE_PIN AH30 [get_ports FB1_RX_LVDS_N[11] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[11] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[11] ]
set_property PACKAGE_PIN T25 [get_ports FB1_RX_LVDS_P[12] ]
set_property PACKAGE_PIN U25 [get_ports FB1_RX_LVDS_N[12] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[12] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[12] ]
set_property PACKAGE_PIN V26 [get_ports FB1_RX_LVDS_P[13] ]
set_property PACKAGE_PIN V27 [get_ports FB1_RX_LVDS_N[13] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[13] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[13] ]
set_property PACKAGE_PIN V29 [get_ports FB1_RX_LVDS_P[14] ]
set_property PACKAGE_PIN V30 [get_ports FB1_RX_LVDS_N[14] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[14] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[14] ]
set_property PACKAGE_PIN P27 [get_ports FB1_RX_LVDS_P[15] ]
set_property PACKAGE_PIN P28 [get_ports FB1_RX_LVDS_N[15] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[15] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[15] ]
set_property PACKAGE_PIN P26 [get_ports FB1_RX_LVDS_P[16] ]
set_property PACKAGE_PIN R26 [get_ports FB1_RX_LVDS_N[16] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[16] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[16] ]
set_property PACKAGE_PIN U29 [get_ports FB1_RX_LVDS_P[17] ]
set_property PACKAGE_PIN U30 [get_ports FB1_RX_LVDS_N[17] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[17] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[17] ]
set_property PACKAGE_PIN U27 [get_ports FB1_RX_LVDS_P[18] ]
set_property PACKAGE_PIN U28 [get_ports FB1_RX_LVDS_N[18] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[18] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[18] ]
set_property PACKAGE_PIN R28 [get_ports FB1_RX_LVDS_P[19] ]
set_property PACKAGE_PIN T28 [get_ports FB1_RX_LVDS_N[19] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[19] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[19] ]
set_property PACKAGE_PIN AA25 [get_ports FB1_RX_LVDS_P[20] ]
set_property PACKAGE_PIN AB25 [get_ports FB1_RX_LVDS_N[20] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[20] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[20] ]
set_property PACKAGE_PIN Y23 [get_ports FB1_RX_LVDS_P[21] ]
set_property PACKAGE_PIN Y24 [get_ports FB1_RX_LVDS_N[21] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[21] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[21] ]
set_property PACKAGE_PIN V25 [get_ports FB1_RX_LVDS_P[22] ]
set_property PACKAGE_PIN W26 [get_ports FB1_RX_LVDS_N[22] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[22] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[22] ]
set_property PACKAGE_PIN R30 [get_ports FB1_RX_LVDS_P[23] ]
set_property PACKAGE_PIN T30 [get_ports FB1_RX_LVDS_N[23] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_P[23] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_RX_LVDS_N[23] ]
set_property PACKAGE_PIN AG29 [get_ports FB1_CLK0_P]
set_property PACKAGE_PIN AH29 [get_ports FB1_CLK0_N]
set_property PACKAGE_PIN AB27 [get_ports FB1_CLK1_P]
set_property PACKAGE_PIN AC27 [get_ports FB1_CLK1_N]
set_property IOSTANDARD LVDS_25 [get_ports FB1_CLK0_P]
set_property IOSTANDARD LVDS_25 [get_ports FB1_CLK0_N]
set_property IOSTANDARD LVDS_25 [get_ports FB1_CLK1_P]
set_property IOSTANDARD LVDS_25 [get_ports FB1_CLK1_N]
set_property PACKAGE_PIN J29 [get_ports FB2_RX_LVDS_P[0] ]
set_property PACKAGE_PIN H29 [get_ports FB2_RX_LVDS_N[0] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[0] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[0] ]
set_property PACKAGE_PIN J27 [get_ports FB2_RX_LVDS_P[1] ]
set_property PACKAGE_PIN J28 [get_ports FB2_RX_LVDS_N[1] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[1] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[1] ]
set_property PACKAGE_PIN H26 [get_ports FB2_RX_LVDS_P[2] ]
set_property PACKAGE_PIN H27 [get_ports FB2_RX_LVDS_N[2] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[2] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[2] ]
set_property PACKAGE_PIN F26 [get_ports FB2_RX_LVDS_P[3] ]
set_property PACKAGE_PIN E26 [get_ports FB2_RX_LVDS_N[3] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[3] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[3] ]
set_property PACKAGE_PIN G28 [get_ports FB2_RX_LVDS_P[4] ]
set_property PACKAGE_PIN F28 [get_ports FB2_RX_LVDS_N[4] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[4] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[4] ]
set_property PACKAGE_PIN B27 [get_ports FB2_RX_LVDS_P[5] ]
set_property PACKAGE_PIN A27 [get_ports FB2_RX_LVDS_N[5] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[5] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[5] ]
set_property PACKAGE_PIN A25 [get_ports FB2_RX_LVDS_P[6] ]
set_property PACKAGE_PIN A26 [get_ports FB2_RX_LVDS_N[6] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[6] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[6] ]
set_property PACKAGE_PIN D26 [get_ports FB2_RX_LVDS_P[7] ]
set_property PACKAGE_PIN C26 [get_ports FB2_RX_LVDS_N[7] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[7] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[7] ]
set_property PACKAGE_PIN N27 [get_ports FB2_RX_LVDS_P[8] ]
set_property PACKAGE_PIN M27 [get_ports FB2_RX_LVDS_N[8] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[8] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[8] ]
set_property PACKAGE_PIN M24 [get_ports FB2_RX_LVDS_P[9] ]
set_property PACKAGE_PIN M25 [get_ports FB2_RX_LVDS_N[9] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[9] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[9] ]
set_property PACKAGE_PIN G29 [get_ports FB2_RX_LVDS_P[10] ]
set_property PACKAGE_PIN F30 [get_ports FB2_RX_LVDS_N[10] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[10] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[10] ]
set_property PACKAGE_PIN C29 [get_ports FB2_RX_LVDS_P[11] ]
set_property PACKAGE_PIN B29 [get_ports FB2_RX_LVDS_N[11] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[11] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[11] ]
set_property PACKAGE_PIN D17 [get_ports FB2_RX_LVDS_P[12] ]
set_property PACKAGE_PIN D18 [get_ports FB2_RX_LVDS_N[12] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[12] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[12] ]
set_property PACKAGE_PIN C20 [get_ports FB2_RX_LVDS_P[13] ]
set_property PACKAGE_PIN B20 [get_ports FB2_RX_LVDS_N[13] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[13] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[13] ]
set_property PACKAGE_PIN C19 [get_ports FB2_RX_LVDS_P[14] ]
set_property PACKAGE_PIN B19 [get_ports FB2_RX_LVDS_N[14] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[14] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[14] ]
set_property PACKAGE_PIN G18 [get_ports FB2_RX_LVDS_P[15] ]
set_property PACKAGE_PIN F18 [get_ports FB2_RX_LVDS_N[15] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[15] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[15] ]
set_property PACKAGE_PIN D22 [get_ports FB2_RX_LVDS_P[16] ]
set_property PACKAGE_PIN C22 [get_ports FB2_RX_LVDS_N[16] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[16] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[16] ]
set_property PACKAGE_PIN E19 [get_ports FB2_RX_LVDS_P[17] ]
set_property PACKAGE_PIN D19 [get_ports FB2_RX_LVDS_N[17] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[17] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[17] ]
set_property PACKAGE_PIN C17 [get_ports FB2_RX_LVDS_P[18] ]
set_property PACKAGE_PIN B17 [get_ports FB2_RX_LVDS_N[18] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[18] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[18] ]
set_property PACKAGE_PIN D16 [get_ports FB2_RX_LVDS_P[19] ]
set_property PACKAGE_PIN C16 [get_ports FB2_RX_LVDS_N[19] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[19] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[19] ]
set_property PACKAGE_PIN E23 [get_ports FB2_RX_LVDS_P[20] ]
set_property PACKAGE_PIN D23 [get_ports FB2_RX_LVDS_N[20] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[20] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[20] ]
set_property PACKAGE_PIN B18 [get_ports FB2_RX_LVDS_P[21] ]
set_property PACKAGE_PIN A18 [get_ports FB2_RX_LVDS_N[21] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[21] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[21] ]
set_property PACKAGE_PIN A16 [get_ports FB2_RX_LVDS_P[22] ]
set_property PACKAGE_PIN A17 [get_ports FB2_RX_LVDS_N[22] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[22] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[22] ]
set_property PACKAGE_PIN F20 [get_ports FB2_RX_LVDS_P[23] ]
set_property PACKAGE_PIN E20 [get_ports FB2_RX_LVDS_N[23] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_P[23] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_RX_LVDS_N[23] ]
set_property PACKAGE_PIN C25 [get_ports FB2_CLK0_P]
set_property PACKAGE_PIN B25 [get_ports FB2_CLK0_N]
set_property PACKAGE_PIN D27 [get_ports FB2_CLK1_P]
set_property PACKAGE_PIN C27 [get_ports FB2_CLK1_N]
set_property IOSTANDARD LVDS_25 [get_ports FB2_CLK0_P]
set_property IOSTANDARD LVDS_25 [get_ports FB2_CLK0_N]
set_property IOSTANDARD LVDS_25 [get_ports FB2_CLK1_P]
set_property IOSTANDARD LVDS_25 [get_ports FB2_CLK1_N]
set_property PACKAGE_PIN AJ28 [get_ports FB1_TX_LVDS_P[0] ]
set_property PACKAGE_PIN AJ29 [get_ports FB1_TX_LVDS_N[0] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_TX_LVDS_P[0] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_TX_LVDS_N[0] ]
set_property PACKAGE_PIN AG20 [get_ports FB1_TX_LVDS_P[1] ]
set_property PACKAGE_PIN AH20 [get_ports FB1_TX_LVDS_N[1] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_TX_LVDS_P[1] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_TX_LVDS_N[1] ]
set_property PACKAGE_PIN W23 [get_ports FB1_TX_LVDS_P[2] ]
set_property PACKAGE_PIN W24 [get_ports FB1_TX_LVDS_N[2] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_TX_LVDS_P[2] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_TX_LVDS_N[2] ]
set_property PACKAGE_PIN Y30 [get_ports FB1_TX_LVDS_P[3] ]
set_property PACKAGE_PIN AA30 [get_ports FB1_TX_LVDS_N[3] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_TX_LVDS_P[3] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_TX_LVDS_N[3] ]
set_property PACKAGE_PIN W27 [get_ports FB1_TX_LVDS_P[4] ]
set_property PACKAGE_PIN W28 [get_ports FB1_TX_LVDS_N[4] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_TX_LVDS_P[4] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_TX_LVDS_N[4] ]
set_property PACKAGE_PIN P29 [get_ports FB1_TX_LVDS_P[5] ]
set_property PACKAGE_PIN R29 [get_ports FB1_TX_LVDS_N[5] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_TX_LVDS_P[5] ]
set_property IOSTANDARD LVDS_25 [get_ports FB1_TX_LVDS_N[5] ]
set_property PACKAGE_PIN AJ24 [get_ports FB1_TX_FWD_CLK_P]
set_property PACKAGE_PIN AK25 [get_ports FB1_TX_FWD_CLK_N]
set_property IOSTANDARD LVDS_25 [get_ports FB1_TX_FWD_CLK_P]
set_property IOSTANDARD LVDS_25 [get_ports FB1_TX_FWD_CLK_N]
set_property PACKAGE_PIN AG24 [get_ports FB1_SOFT_RESET0_P]
set_property PACKAGE_PIN AH24 [get_ports FB1_SOFT_RESET0_N]
set_property IOSTANDARD LVDS_25 [get_ports FB1_SOFT_RESET0_P]
set_property IOSTANDARD LVDS_25 [get_ports FB1_SOFT_RESET0_N]
set_property PACKAGE_PIN Y26 [get_ports FB1_SOFT_RESET1_P]
set_property PACKAGE_PIN AA26 [get_ports FB1_SOFT_RESET1_N]
set_property IOSTANDARD LVDS_25 [get_ports FB1_SOFT_RESET1_P]
set_property IOSTANDARD LVDS_25 [get_ports FB1_SOFT_RESET1_N]
set_property PACKAGE_PIN E29 [get_ports FB2_TX_LVDS_P[0] ]
set_property PACKAGE_PIN E30 [get_ports FB2_TX_LVDS_N[0] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_TX_LVDS_P[0] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_TX_LVDS_N[0] ]
set_property PACKAGE_PIN N25 [get_ports FB2_TX_LVDS_P[1] ]
set_property PACKAGE_PIN N26 [get_ports FB2_TX_LVDS_N[1] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_TX_LVDS_P[1] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_TX_LVDS_N[1] ]
set_property PACKAGE_PIN F25 [get_ports FB2_TX_LVDS_P[2] ]
set_property PACKAGE_PIN E25 [get_ports FB2_TX_LVDS_N[2] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_TX_LVDS_P[2] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_TX_LVDS_N[2] ]
set_property PACKAGE_PIN B22 [get_ports FB2_TX_LVDS_P[3] ]
set_property PACKAGE_PIN A22 [get_ports FB2_TX_LVDS_N[3] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_TX_LVDS_P[3] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_TX_LVDS_N[3] ]
set_property PACKAGE_PIN D21 [get_ports FB2_TX_LVDS_P[4] ]
set_property PACKAGE_PIN C21 [get_ports FB2_TX_LVDS_N[4] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_TX_LVDS_P[4] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_TX_LVDS_N[4] ]
set_property PACKAGE_PIN G17 [get_ports FB2_TX_LVDS_P[5] ]
set_property PACKAGE_PIN F17 [get_ports FB2_TX_LVDS_N[5] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_TX_LVDS_P[5] ]
set_property IOSTANDARD LVDS_25 [get_ports FB2_TX_LVDS_N[5] ]
set_property PACKAGE_PIN K28 [get_ports FB2_TX_FWD_CLK_P]
set_property PACKAGE_PIN K29 [get_ports FB2_TX_FWD_CLK_N]
set_property IOSTANDARD LVDS_25 [get_ports FB2_TX_FWD_CLK_P]
set_property IOSTANDARD LVDS_25 [get_ports FB2_TX_FWD_CLK_N]
set_property PACKAGE_PIN K23 [get_ports FB2_SOFT_RESET0_P]
set_property PACKAGE_PIN K24 [get_ports FB2_SOFT_RESET0_N]
set_property IOSTANDARD LVDS_25 [get_ports FB2_SOFT_RESET0_P]
set_property IOSTANDARD LVDS_25 [get_ports FB2_SOFT_RESET0_N]
set_property PACKAGE_PIN A20 [get_ports FB2_SOFT_RESET1_P]
set_property PACKAGE_PIN A21 [get_ports FB2_SOFT_RESET1_N]
set_property IOSTANDARD LVDS_25 [get_ports FB2_SOFT_RESET1_P]
set_property IOSTANDARD LVDS_25 [get_ports FB2_SOFT_RESET1_N]

##################################
# physical constraint (pin location)

set_property PACKAGE_PIN AH4 [get_ports SYSCLK_P]
set_property PACKAGE_PIN AJ4 [get_ports SYSCLK_N]


set_property PACKAGE_PIN G12 [get_ports MISO]
set_property PACKAGE_PIN F16 [get_ports MOSI]
set_property PACKAGE_PIN H12 [get_ports SPI_SEL]
set_property PACKAGE_PIN H14 [get_ports SCLK]

# physical constraint (iostandard)

set_property IOSTANDARD LVDS [get_ports SYSCLK_P]
set_property IOSTANDARD LVDS [get_ports SYSCLK_N]

set_property IOSTANDARD LVCMOS25 [get_ports MISO]
set_property IOSTANDARD LVCMOS25 [get_ports MOSI]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_SEL]
set_property IOSTANDARD LVCMOS25 [get_ports SCLK]


create_clock -name sysclk_p_i    -period 5      -waveform {0 2.5}   [get_ports SYSCLK_P]
create_clock -name fb1_clk0_p_i  -period 5      -waveform {0 2.5}   [get_ports FB1_CLK0_P]
create_clock -name fb1_clk1_p_i  -period 5      -waveform {0 2.5}   [get_ports FB1_CLK1_P]
create_clock -name fb2_clk0_p_i  -period 5      -waveform {0 2.5}   [get_ports FB2_CLK0_P]
create_clock -name fb2_clk1_p_i  -period 5      -waveform {0 2.5}   [get_ports FB2_CLK1_P]


# # timing constraint
# NET "RX_FROM_IM_FPGAS[0].FMC_INTERFACE/FRONT/buf200/clkin1_delay" TNM_NET = "fb1_fpga0";
# TIMESPEC "TS_fb1_fpga0" = PERIOD "fb1_fpga0" 200 MHz HIGH 50%;

# NET "RX_FROM_IM_FPGAS[1].FMC_INTERFACE/FRONT/buf200/clkin1_delay" TNM_NET = "fb1_fpga1";
# TIMESPEC "TS_fb1_fpga1" = PERIOD "fb1_fpga1" 200 MHz HIGH 50%;

# NET "RX_FROM_IM_FPGAS[2].FMC_INTERFACE/FRONT/buf200/clkin1_delay" TNM_NET = "fb2_fpga0";
# TIMESPEC "TS_fb2_fpga0" = PERIOD "fb2_fpga0" 200 MHz HIGH 50%;

# NET "RX_FROM_IM_FPGAS[3].FMC_INTERFACE/FRONT/buf200/clkin1_delay" TNM_NET = "fb2_fpga1";
# TIMESPEC "TS_fb2_fpga1" = PERIOD "fb2_fpga1" 200 MHz HIGH 50%;

# NET "RX_FROM_IM_FPGAS[4].FMC_INTERFACE/FRONT/buf200/clkin1_delay" TNM_NET = "fb3_fpga0";
# TIMESPEC "TS_fb3_fpga0" = PERIOD "fb3_fpga0" 200 MHz HIGH 50%;

# NET "RX_FROM_IM_FPGAS[5].FMC_INTERFACE/FRONT/buf200/clkin1_delay" TNM_NET = "fb3_fpga1";
# TIMESPEC "TS_fb3_fpga1" = PERIOD "fb3_fpga1" 200 MHz HIGH 50%;

# NET "RX_FROM_IM_FPGAS[6].FMC_INTERFACE/FRONT/buf200/clkin1_delay" TNM_NET = "fb4_fpga0";
# TIMESPEC "TS_fb4_fpga0" = PERIOD "fb4_fpga0" 200 MHz HIGH 50%;

# NET "RX_FROM_IM_FPGAS[7].FMC_INTERFACE/FRONT/buf200/clkin1_delay" TNM_NET = "fb4_fpga1";
# TIMESPEC "TS_fb4_fpga1" = PERIOD "fb4_fpga1" 200 MHz HIGH 50%;


# NET "fmc_common_clk_i" TNM_NET = "fmc_common_clk_i"; TIMESPEC "TS_fmc_common_clk_i" = PERIOD "fmc_common_clk_i" 200 MHz HIGH 50%;
