-- Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2014.2 (win64) Build 928826 Thu Jun  5 18:17:50 MDT 2014
-- Date        : Wed Aug 13 02:36:49 2014
-- Host        : PC-UC-FTK-FW running 64-bit Service Pack 1  (build 7601)
-- Command     : write_vhdl -force -mode synth_stub
--               C:/cygwin64/home/okumura/firmware_vivado/ipcore/xc7vx690t-ffg1927-2/gt625_fab20/gt625_fab20_stub.vhdl
-- Design      : gt625_fab20
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7vx690tffg1927-2
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity gt625_fab20 is
  Port ( 
    SYSCLK_IN : in STD_LOGIC;
    SOFT_RESET_IN : in STD_LOGIC;
    DONT_RESET_ON_DATA_ERROR_IN : in STD_LOGIC;
    GT0_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT0_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT0_DATA_VALID_IN : in STD_LOGIC;
    GT1_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT1_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT1_DATA_VALID_IN : in STD_LOGIC;
    GT2_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT2_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT2_DATA_VALID_IN : in STD_LOGIC;
    GT3_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT3_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT3_DATA_VALID_IN : in STD_LOGIC;
    GT4_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT4_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT4_DATA_VALID_IN : in STD_LOGIC;
    GT5_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT5_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT5_DATA_VALID_IN : in STD_LOGIC;
    GT6_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT6_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT6_DATA_VALID_IN : in STD_LOGIC;
    GT7_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT7_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT7_DATA_VALID_IN : in STD_LOGIC;
    GT8_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT8_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT8_DATA_VALID_IN : in STD_LOGIC;
    GT9_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT9_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT9_DATA_VALID_IN : in STD_LOGIC;
    GT10_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT10_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT10_DATA_VALID_IN : in STD_LOGIC;
    GT11_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT11_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT11_DATA_VALID_IN : in STD_LOGIC;
    GT12_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT12_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT12_DATA_VALID_IN : in STD_LOGIC;
    GT13_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT13_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT13_DATA_VALID_IN : in STD_LOGIC;
    GT14_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT14_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT14_DATA_VALID_IN : in STD_LOGIC;
    GT15_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT15_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT15_DATA_VALID_IN : in STD_LOGIC;
    GT16_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT16_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT16_DATA_VALID_IN : in STD_LOGIC;
    GT17_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT17_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT17_DATA_VALID_IN : in STD_LOGIC;
    GT18_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT18_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT18_DATA_VALID_IN : in STD_LOGIC;
    GT19_TX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT19_RX_FSM_RESET_DONE_OUT : out STD_LOGIC;
    GT19_DATA_VALID_IN : in STD_LOGIC;
    gt0_cpllfbclklost_out : out STD_LOGIC;
    gt0_cplllock_out : out STD_LOGIC;
    gt0_cplllockdetclk_in : in STD_LOGIC;
    gt0_cpllreset_in : in STD_LOGIC;
    gt0_gtrefclk0_in : in STD_LOGIC;
    gt0_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt0_drpclk_in : in STD_LOGIC;
    gt0_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt0_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt0_drpen_in : in STD_LOGIC;
    gt0_drprdy_out : out STD_LOGIC;
    gt0_drpwe_in : in STD_LOGIC;
    gt0_eyescanreset_in : in STD_LOGIC;
    gt0_rxuserrdy_in : in STD_LOGIC;
    gt0_eyescandataerror_out : out STD_LOGIC;
    gt0_eyescantrigger_in : in STD_LOGIC;
    gt0_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt0_rxusrclk_in : in STD_LOGIC;
    gt0_rxusrclk2_in : in STD_LOGIC;
    gt0_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt0_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt0_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt0_gthrxn_in : in STD_LOGIC;
    gt0_rxbyteisaligned_out : out STD_LOGIC;
    gt0_rxmcommaalignen_in : in STD_LOGIC;
    gt0_rxpcommaalignen_in : in STD_LOGIC;
    gt0_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt0_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt0_gtrxreset_in : in STD_LOGIC;
    gt0_rxpolarity_in : in STD_LOGIC;
    gt0_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt0_gthrxp_in : in STD_LOGIC;
    gt0_rxresetdone_out : out STD_LOGIC;
    gt0_gttxreset_in : in STD_LOGIC;
    gt0_txuserrdy_in : in STD_LOGIC;
    gt0_txusrclk_in : in STD_LOGIC;
    gt0_txusrclk2_in : in STD_LOGIC;
    gt0_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt0_gthtxn_out : out STD_LOGIC;
    gt0_gthtxp_out : out STD_LOGIC;
    gt0_txoutclk_out : out STD_LOGIC;
    gt0_txoutclkfabric_out : out STD_LOGIC;
    gt0_txoutclkpcs_out : out STD_LOGIC;
    gt0_txresetdone_out : out STD_LOGIC;
    gt0_txpolarity_in : in STD_LOGIC;
    gt0_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt1_cpllfbclklost_out : out STD_LOGIC;
    gt1_cplllock_out : out STD_LOGIC;
    gt1_cplllockdetclk_in : in STD_LOGIC;
    gt1_cpllreset_in : in STD_LOGIC;
    gt1_gtrefclk0_in : in STD_LOGIC;
    gt1_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt1_drpclk_in : in STD_LOGIC;
    gt1_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt1_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt1_drpen_in : in STD_LOGIC;
    gt1_drprdy_out : out STD_LOGIC;
    gt1_drpwe_in : in STD_LOGIC;
    gt1_eyescanreset_in : in STD_LOGIC;
    gt1_rxuserrdy_in : in STD_LOGIC;
    gt1_eyescandataerror_out : out STD_LOGIC;
    gt1_eyescantrigger_in : in STD_LOGIC;
    gt1_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt1_rxusrclk_in : in STD_LOGIC;
    gt1_rxusrclk2_in : in STD_LOGIC;
    gt1_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt1_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt1_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt1_gthrxn_in : in STD_LOGIC;
    gt1_rxbyteisaligned_out : out STD_LOGIC;
    gt1_rxmcommaalignen_in : in STD_LOGIC;
    gt1_rxpcommaalignen_in : in STD_LOGIC;
    gt1_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt1_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt1_gtrxreset_in : in STD_LOGIC;
    gt1_rxpolarity_in : in STD_LOGIC;
    gt1_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt1_gthrxp_in : in STD_LOGIC;
    gt1_rxresetdone_out : out STD_LOGIC;
    gt1_gttxreset_in : in STD_LOGIC;
    gt1_txuserrdy_in : in STD_LOGIC;
    gt1_txusrclk_in : in STD_LOGIC;
    gt1_txusrclk2_in : in STD_LOGIC;
    gt1_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt1_gthtxn_out : out STD_LOGIC;
    gt1_gthtxp_out : out STD_LOGIC;
    gt1_txoutclk_out : out STD_LOGIC;
    gt1_txoutclkfabric_out : out STD_LOGIC;
    gt1_txoutclkpcs_out : out STD_LOGIC;
    gt1_txresetdone_out : out STD_LOGIC;
    gt1_txpolarity_in : in STD_LOGIC;
    gt1_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt2_cpllfbclklost_out : out STD_LOGIC;
    gt2_cplllock_out : out STD_LOGIC;
    gt2_cplllockdetclk_in : in STD_LOGIC;
    gt2_cpllreset_in : in STD_LOGIC;
    gt2_gtrefclk0_in : in STD_LOGIC;
    gt2_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt2_drpclk_in : in STD_LOGIC;
    gt2_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt2_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt2_drpen_in : in STD_LOGIC;
    gt2_drprdy_out : out STD_LOGIC;
    gt2_drpwe_in : in STD_LOGIC;
    gt2_eyescanreset_in : in STD_LOGIC;
    gt2_rxuserrdy_in : in STD_LOGIC;
    gt2_eyescandataerror_out : out STD_LOGIC;
    gt2_eyescantrigger_in : in STD_LOGIC;
    gt2_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt2_rxusrclk_in : in STD_LOGIC;
    gt2_rxusrclk2_in : in STD_LOGIC;
    gt2_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt2_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt2_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt2_gthrxn_in : in STD_LOGIC;
    gt2_rxbyteisaligned_out : out STD_LOGIC;
    gt2_rxmcommaalignen_in : in STD_LOGIC;
    gt2_rxpcommaalignen_in : in STD_LOGIC;
    gt2_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt2_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt2_gtrxreset_in : in STD_LOGIC;
    gt2_rxpolarity_in : in STD_LOGIC;
    gt2_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt2_gthrxp_in : in STD_LOGIC;
    gt2_rxresetdone_out : out STD_LOGIC;
    gt2_gttxreset_in : in STD_LOGIC;
    gt2_txuserrdy_in : in STD_LOGIC;
    gt2_txusrclk_in : in STD_LOGIC;
    gt2_txusrclk2_in : in STD_LOGIC;
    gt2_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt2_gthtxn_out : out STD_LOGIC;
    gt2_gthtxp_out : out STD_LOGIC;
    gt2_txoutclk_out : out STD_LOGIC;
    gt2_txoutclkfabric_out : out STD_LOGIC;
    gt2_txoutclkpcs_out : out STD_LOGIC;
    gt2_txresetdone_out : out STD_LOGIC;
    gt2_txpolarity_in : in STD_LOGIC;
    gt2_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt3_cpllfbclklost_out : out STD_LOGIC;
    gt3_cplllock_out : out STD_LOGIC;
    gt3_cplllockdetclk_in : in STD_LOGIC;
    gt3_cpllreset_in : in STD_LOGIC;
    gt3_gtrefclk0_in : in STD_LOGIC;
    gt3_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt3_drpclk_in : in STD_LOGIC;
    gt3_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt3_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt3_drpen_in : in STD_LOGIC;
    gt3_drprdy_out : out STD_LOGIC;
    gt3_drpwe_in : in STD_LOGIC;
    gt3_eyescanreset_in : in STD_LOGIC;
    gt3_rxuserrdy_in : in STD_LOGIC;
    gt3_eyescandataerror_out : out STD_LOGIC;
    gt3_eyescantrigger_in : in STD_LOGIC;
    gt3_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt3_rxusrclk_in : in STD_LOGIC;
    gt3_rxusrclk2_in : in STD_LOGIC;
    gt3_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt3_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt3_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt3_gthrxn_in : in STD_LOGIC;
    gt3_rxbyteisaligned_out : out STD_LOGIC;
    gt3_rxmcommaalignen_in : in STD_LOGIC;
    gt3_rxpcommaalignen_in : in STD_LOGIC;
    gt3_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt3_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt3_gtrxreset_in : in STD_LOGIC;
    gt3_rxpolarity_in : in STD_LOGIC;
    gt3_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt3_gthrxp_in : in STD_LOGIC;
    gt3_rxresetdone_out : out STD_LOGIC;
    gt3_gttxreset_in : in STD_LOGIC;
    gt3_txuserrdy_in : in STD_LOGIC;
    gt3_txusrclk_in : in STD_LOGIC;
    gt3_txusrclk2_in : in STD_LOGIC;
    gt3_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt3_gthtxn_out : out STD_LOGIC;
    gt3_gthtxp_out : out STD_LOGIC;
    gt3_txoutclk_out : out STD_LOGIC;
    gt3_txoutclkfabric_out : out STD_LOGIC;
    gt3_txoutclkpcs_out : out STD_LOGIC;
    gt3_txresetdone_out : out STD_LOGIC;
    gt3_txpolarity_in : in STD_LOGIC;
    gt3_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt4_cpllfbclklost_out : out STD_LOGIC;
    gt4_cplllock_out : out STD_LOGIC;
    gt4_cplllockdetclk_in : in STD_LOGIC;
    gt4_cpllreset_in : in STD_LOGIC;
    gt4_gtrefclk0_in : in STD_LOGIC;
    gt4_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt4_drpclk_in : in STD_LOGIC;
    gt4_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt4_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt4_drpen_in : in STD_LOGIC;
    gt4_drprdy_out : out STD_LOGIC;
    gt4_drpwe_in : in STD_LOGIC;
    gt4_eyescanreset_in : in STD_LOGIC;
    gt4_rxuserrdy_in : in STD_LOGIC;
    gt4_eyescandataerror_out : out STD_LOGIC;
    gt4_eyescantrigger_in : in STD_LOGIC;
    gt4_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt4_rxusrclk_in : in STD_LOGIC;
    gt4_rxusrclk2_in : in STD_LOGIC;
    gt4_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt4_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt4_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt4_gthrxn_in : in STD_LOGIC;
    gt4_rxbyteisaligned_out : out STD_LOGIC;
    gt4_rxmcommaalignen_in : in STD_LOGIC;
    gt4_rxpcommaalignen_in : in STD_LOGIC;
    gt4_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt4_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt4_gtrxreset_in : in STD_LOGIC;
    gt4_rxpolarity_in : in STD_LOGIC;
    gt4_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt4_gthrxp_in : in STD_LOGIC;
    gt4_rxresetdone_out : out STD_LOGIC;
    gt4_gttxreset_in : in STD_LOGIC;
    gt4_txuserrdy_in : in STD_LOGIC;
    gt4_txusrclk_in : in STD_LOGIC;
    gt4_txusrclk2_in : in STD_LOGIC;
    gt4_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt4_gthtxn_out : out STD_LOGIC;
    gt4_gthtxp_out : out STD_LOGIC;
    gt4_txoutclk_out : out STD_LOGIC;
    gt4_txoutclkfabric_out : out STD_LOGIC;
    gt4_txoutclkpcs_out : out STD_LOGIC;
    gt4_txresetdone_out : out STD_LOGIC;
    gt4_txpolarity_in : in STD_LOGIC;
    gt4_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt5_cpllfbclklost_out : out STD_LOGIC;
    gt5_cplllock_out : out STD_LOGIC;
    gt5_cplllockdetclk_in : in STD_LOGIC;
    gt5_cpllreset_in : in STD_LOGIC;
    gt5_gtrefclk0_in : in STD_LOGIC;
    gt5_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt5_drpclk_in : in STD_LOGIC;
    gt5_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt5_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt5_drpen_in : in STD_LOGIC;
    gt5_drprdy_out : out STD_LOGIC;
    gt5_drpwe_in : in STD_LOGIC;
    gt5_eyescanreset_in : in STD_LOGIC;
    gt5_rxuserrdy_in : in STD_LOGIC;
    gt5_eyescandataerror_out : out STD_LOGIC;
    gt5_eyescantrigger_in : in STD_LOGIC;
    gt5_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt5_rxusrclk_in : in STD_LOGIC;
    gt5_rxusrclk2_in : in STD_LOGIC;
    gt5_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt5_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt5_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt5_gthrxn_in : in STD_LOGIC;
    gt5_rxbyteisaligned_out : out STD_LOGIC;
    gt5_rxmcommaalignen_in : in STD_LOGIC;
    gt5_rxpcommaalignen_in : in STD_LOGIC;
    gt5_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt5_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt5_gtrxreset_in : in STD_LOGIC;
    gt5_rxpolarity_in : in STD_LOGIC;
    gt5_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt5_gthrxp_in : in STD_LOGIC;
    gt5_rxresetdone_out : out STD_LOGIC;
    gt5_gttxreset_in : in STD_LOGIC;
    gt5_txuserrdy_in : in STD_LOGIC;
    gt5_txusrclk_in : in STD_LOGIC;
    gt5_txusrclk2_in : in STD_LOGIC;
    gt5_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt5_gthtxn_out : out STD_LOGIC;
    gt5_gthtxp_out : out STD_LOGIC;
    gt5_txoutclk_out : out STD_LOGIC;
    gt5_txoutclkfabric_out : out STD_LOGIC;
    gt5_txoutclkpcs_out : out STD_LOGIC;
    gt5_txresetdone_out : out STD_LOGIC;
    gt5_txpolarity_in : in STD_LOGIC;
    gt5_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt6_cpllfbclklost_out : out STD_LOGIC;
    gt6_cplllock_out : out STD_LOGIC;
    gt6_cplllockdetclk_in : in STD_LOGIC;
    gt6_cpllreset_in : in STD_LOGIC;
    gt6_gtrefclk0_in : in STD_LOGIC;
    gt6_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt6_drpclk_in : in STD_LOGIC;
    gt6_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt6_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt6_drpen_in : in STD_LOGIC;
    gt6_drprdy_out : out STD_LOGIC;
    gt6_drpwe_in : in STD_LOGIC;
    gt6_eyescanreset_in : in STD_LOGIC;
    gt6_rxuserrdy_in : in STD_LOGIC;
    gt6_eyescandataerror_out : out STD_LOGIC;
    gt6_eyescantrigger_in : in STD_LOGIC;
    gt6_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt6_rxusrclk_in : in STD_LOGIC;
    gt6_rxusrclk2_in : in STD_LOGIC;
    gt6_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt6_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt6_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt6_gthrxn_in : in STD_LOGIC;
    gt6_rxbyteisaligned_out : out STD_LOGIC;
    gt6_rxmcommaalignen_in : in STD_LOGIC;
    gt6_rxpcommaalignen_in : in STD_LOGIC;
    gt6_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt6_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt6_gtrxreset_in : in STD_LOGIC;
    gt6_rxpolarity_in : in STD_LOGIC;
    gt6_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt6_gthrxp_in : in STD_LOGIC;
    gt6_rxresetdone_out : out STD_LOGIC;
    gt6_gttxreset_in : in STD_LOGIC;
    gt6_txuserrdy_in : in STD_LOGIC;
    gt6_txusrclk_in : in STD_LOGIC;
    gt6_txusrclk2_in : in STD_LOGIC;
    gt6_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt6_gthtxn_out : out STD_LOGIC;
    gt6_gthtxp_out : out STD_LOGIC;
    gt6_txoutclk_out : out STD_LOGIC;
    gt6_txoutclkfabric_out : out STD_LOGIC;
    gt6_txoutclkpcs_out : out STD_LOGIC;
    gt6_txresetdone_out : out STD_LOGIC;
    gt6_txpolarity_in : in STD_LOGIC;
    gt6_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt7_cpllfbclklost_out : out STD_LOGIC;
    gt7_cplllock_out : out STD_LOGIC;
    gt7_cplllockdetclk_in : in STD_LOGIC;
    gt7_cpllreset_in : in STD_LOGIC;
    gt7_gtrefclk0_in : in STD_LOGIC;
    gt7_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt7_drpclk_in : in STD_LOGIC;
    gt7_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt7_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt7_drpen_in : in STD_LOGIC;
    gt7_drprdy_out : out STD_LOGIC;
    gt7_drpwe_in : in STD_LOGIC;
    gt7_eyescanreset_in : in STD_LOGIC;
    gt7_rxuserrdy_in : in STD_LOGIC;
    gt7_eyescandataerror_out : out STD_LOGIC;
    gt7_eyescantrigger_in : in STD_LOGIC;
    gt7_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt7_rxusrclk_in : in STD_LOGIC;
    gt7_rxusrclk2_in : in STD_LOGIC;
    gt7_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt7_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt7_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt7_gthrxn_in : in STD_LOGIC;
    gt7_rxbyteisaligned_out : out STD_LOGIC;
    gt7_rxmcommaalignen_in : in STD_LOGIC;
    gt7_rxpcommaalignen_in : in STD_LOGIC;
    gt7_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt7_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt7_gtrxreset_in : in STD_LOGIC;
    gt7_rxpolarity_in : in STD_LOGIC;
    gt7_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt7_gthrxp_in : in STD_LOGIC;
    gt7_rxresetdone_out : out STD_LOGIC;
    gt7_gttxreset_in : in STD_LOGIC;
    gt7_txuserrdy_in : in STD_LOGIC;
    gt7_txusrclk_in : in STD_LOGIC;
    gt7_txusrclk2_in : in STD_LOGIC;
    gt7_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt7_gthtxn_out : out STD_LOGIC;
    gt7_gthtxp_out : out STD_LOGIC;
    gt7_txoutclk_out : out STD_LOGIC;
    gt7_txoutclkfabric_out : out STD_LOGIC;
    gt7_txoutclkpcs_out : out STD_LOGIC;
    gt7_txresetdone_out : out STD_LOGIC;
    gt7_txpolarity_in : in STD_LOGIC;
    gt7_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt8_cpllfbclklost_out : out STD_LOGIC;
    gt8_cplllock_out : out STD_LOGIC;
    gt8_cplllockdetclk_in : in STD_LOGIC;
    gt8_cpllreset_in : in STD_LOGIC;
    gt8_gtrefclk0_in : in STD_LOGIC;
    gt8_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt8_drpclk_in : in STD_LOGIC;
    gt8_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt8_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt8_drpen_in : in STD_LOGIC;
    gt8_drprdy_out : out STD_LOGIC;
    gt8_drpwe_in : in STD_LOGIC;
    gt8_eyescanreset_in : in STD_LOGIC;
    gt8_rxuserrdy_in : in STD_LOGIC;
    gt8_eyescandataerror_out : out STD_LOGIC;
    gt8_eyescantrigger_in : in STD_LOGIC;
    gt8_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt8_rxusrclk_in : in STD_LOGIC;
    gt8_rxusrclk2_in : in STD_LOGIC;
    gt8_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt8_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt8_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt8_gthrxn_in : in STD_LOGIC;
    gt8_rxbyteisaligned_out : out STD_LOGIC;
    gt8_rxmcommaalignen_in : in STD_LOGIC;
    gt8_rxpcommaalignen_in : in STD_LOGIC;
    gt8_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt8_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt8_gtrxreset_in : in STD_LOGIC;
    gt8_rxpolarity_in : in STD_LOGIC;
    gt8_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt8_gthrxp_in : in STD_LOGIC;
    gt8_rxresetdone_out : out STD_LOGIC;
    gt8_gttxreset_in : in STD_LOGIC;
    gt8_txuserrdy_in : in STD_LOGIC;
    gt8_txusrclk_in : in STD_LOGIC;
    gt8_txusrclk2_in : in STD_LOGIC;
    gt8_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt8_gthtxn_out : out STD_LOGIC;
    gt8_gthtxp_out : out STD_LOGIC;
    gt8_txoutclk_out : out STD_LOGIC;
    gt8_txoutclkfabric_out : out STD_LOGIC;
    gt8_txoutclkpcs_out : out STD_LOGIC;
    gt8_txresetdone_out : out STD_LOGIC;
    gt8_txpolarity_in : in STD_LOGIC;
    gt8_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt9_cpllfbclklost_out : out STD_LOGIC;
    gt9_cplllock_out : out STD_LOGIC;
    gt9_cplllockdetclk_in : in STD_LOGIC;
    gt9_cpllreset_in : in STD_LOGIC;
    gt9_gtrefclk0_in : in STD_LOGIC;
    gt9_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt9_drpclk_in : in STD_LOGIC;
    gt9_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt9_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt9_drpen_in : in STD_LOGIC;
    gt9_drprdy_out : out STD_LOGIC;
    gt9_drpwe_in : in STD_LOGIC;
    gt9_eyescanreset_in : in STD_LOGIC;
    gt9_rxuserrdy_in : in STD_LOGIC;
    gt9_eyescandataerror_out : out STD_LOGIC;
    gt9_eyescantrigger_in : in STD_LOGIC;
    gt9_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt9_rxusrclk_in : in STD_LOGIC;
    gt9_rxusrclk2_in : in STD_LOGIC;
    gt9_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt9_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt9_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt9_gthrxn_in : in STD_LOGIC;
    gt9_rxbyteisaligned_out : out STD_LOGIC;
    gt9_rxmcommaalignen_in : in STD_LOGIC;
    gt9_rxpcommaalignen_in : in STD_LOGIC;
    gt9_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt9_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt9_gtrxreset_in : in STD_LOGIC;
    gt9_rxpolarity_in : in STD_LOGIC;
    gt9_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt9_gthrxp_in : in STD_LOGIC;
    gt9_rxresetdone_out : out STD_LOGIC;
    gt9_gttxreset_in : in STD_LOGIC;
    gt9_txuserrdy_in : in STD_LOGIC;
    gt9_txusrclk_in : in STD_LOGIC;
    gt9_txusrclk2_in : in STD_LOGIC;
    gt9_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt9_gthtxn_out : out STD_LOGIC;
    gt9_gthtxp_out : out STD_LOGIC;
    gt9_txoutclk_out : out STD_LOGIC;
    gt9_txoutclkfabric_out : out STD_LOGIC;
    gt9_txoutclkpcs_out : out STD_LOGIC;
    gt9_txresetdone_out : out STD_LOGIC;
    gt9_txpolarity_in : in STD_LOGIC;
    gt9_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt10_cpllfbclklost_out : out STD_LOGIC;
    gt10_cplllock_out : out STD_LOGIC;
    gt10_cplllockdetclk_in : in STD_LOGIC;
    gt10_cpllreset_in : in STD_LOGIC;
    gt10_gtrefclk0_in : in STD_LOGIC;
    gt10_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt10_drpclk_in : in STD_LOGIC;
    gt10_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt10_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt10_drpen_in : in STD_LOGIC;
    gt10_drprdy_out : out STD_LOGIC;
    gt10_drpwe_in : in STD_LOGIC;
    gt10_eyescanreset_in : in STD_LOGIC;
    gt10_rxuserrdy_in : in STD_LOGIC;
    gt10_eyescandataerror_out : out STD_LOGIC;
    gt10_eyescantrigger_in : in STD_LOGIC;
    gt10_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt10_rxusrclk_in : in STD_LOGIC;
    gt10_rxusrclk2_in : in STD_LOGIC;
    gt10_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt10_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt10_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt10_gthrxn_in : in STD_LOGIC;
    gt10_rxbyteisaligned_out : out STD_LOGIC;
    gt10_rxmcommaalignen_in : in STD_LOGIC;
    gt10_rxpcommaalignen_in : in STD_LOGIC;
    gt10_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt10_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt10_gtrxreset_in : in STD_LOGIC;
    gt10_rxpolarity_in : in STD_LOGIC;
    gt10_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt10_gthrxp_in : in STD_LOGIC;
    gt10_rxresetdone_out : out STD_LOGIC;
    gt10_gttxreset_in : in STD_LOGIC;
    gt10_txuserrdy_in : in STD_LOGIC;
    gt10_txusrclk_in : in STD_LOGIC;
    gt10_txusrclk2_in : in STD_LOGIC;
    gt10_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt10_gthtxn_out : out STD_LOGIC;
    gt10_gthtxp_out : out STD_LOGIC;
    gt10_txoutclk_out : out STD_LOGIC;
    gt10_txoutclkfabric_out : out STD_LOGIC;
    gt10_txoutclkpcs_out : out STD_LOGIC;
    gt10_txresetdone_out : out STD_LOGIC;
    gt10_txpolarity_in : in STD_LOGIC;
    gt10_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt11_cpllfbclklost_out : out STD_LOGIC;
    gt11_cplllock_out : out STD_LOGIC;
    gt11_cplllockdetclk_in : in STD_LOGIC;
    gt11_cpllreset_in : in STD_LOGIC;
    gt11_gtrefclk0_in : in STD_LOGIC;
    gt11_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt11_drpclk_in : in STD_LOGIC;
    gt11_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt11_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt11_drpen_in : in STD_LOGIC;
    gt11_drprdy_out : out STD_LOGIC;
    gt11_drpwe_in : in STD_LOGIC;
    gt11_eyescanreset_in : in STD_LOGIC;
    gt11_rxuserrdy_in : in STD_LOGIC;
    gt11_eyescandataerror_out : out STD_LOGIC;
    gt11_eyescantrigger_in : in STD_LOGIC;
    gt11_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt11_rxusrclk_in : in STD_LOGIC;
    gt11_rxusrclk2_in : in STD_LOGIC;
    gt11_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt11_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt11_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt11_gthrxn_in : in STD_LOGIC;
    gt11_rxbyteisaligned_out : out STD_LOGIC;
    gt11_rxmcommaalignen_in : in STD_LOGIC;
    gt11_rxpcommaalignen_in : in STD_LOGIC;
    gt11_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt11_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt11_gtrxreset_in : in STD_LOGIC;
    gt11_rxpolarity_in : in STD_LOGIC;
    gt11_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt11_gthrxp_in : in STD_LOGIC;
    gt11_rxresetdone_out : out STD_LOGIC;
    gt11_gttxreset_in : in STD_LOGIC;
    gt11_txuserrdy_in : in STD_LOGIC;
    gt11_txusrclk_in : in STD_LOGIC;
    gt11_txusrclk2_in : in STD_LOGIC;
    gt11_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt11_gthtxn_out : out STD_LOGIC;
    gt11_gthtxp_out : out STD_LOGIC;
    gt11_txoutclk_out : out STD_LOGIC;
    gt11_txoutclkfabric_out : out STD_LOGIC;
    gt11_txoutclkpcs_out : out STD_LOGIC;
    gt11_txresetdone_out : out STD_LOGIC;
    gt11_txpolarity_in : in STD_LOGIC;
    gt11_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt12_cpllfbclklost_out : out STD_LOGIC;
    gt12_cplllock_out : out STD_LOGIC;
    gt12_cplllockdetclk_in : in STD_LOGIC;
    gt12_cpllreset_in : in STD_LOGIC;
    gt12_gtrefclk0_in : in STD_LOGIC;
    gt12_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt12_drpclk_in : in STD_LOGIC;
    gt12_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt12_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt12_drpen_in : in STD_LOGIC;
    gt12_drprdy_out : out STD_LOGIC;
    gt12_drpwe_in : in STD_LOGIC;
    gt12_eyescanreset_in : in STD_LOGIC;
    gt12_rxuserrdy_in : in STD_LOGIC;
    gt12_eyescandataerror_out : out STD_LOGIC;
    gt12_eyescantrigger_in : in STD_LOGIC;
    gt12_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt12_rxusrclk_in : in STD_LOGIC;
    gt12_rxusrclk2_in : in STD_LOGIC;
    gt12_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt12_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt12_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt12_gthrxn_in : in STD_LOGIC;
    gt12_rxbyteisaligned_out : out STD_LOGIC;
    gt12_rxmcommaalignen_in : in STD_LOGIC;
    gt12_rxpcommaalignen_in : in STD_LOGIC;
    gt12_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt12_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt12_gtrxreset_in : in STD_LOGIC;
    gt12_rxpolarity_in : in STD_LOGIC;
    gt12_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt12_gthrxp_in : in STD_LOGIC;
    gt12_rxresetdone_out : out STD_LOGIC;
    gt12_gttxreset_in : in STD_LOGIC;
    gt12_txuserrdy_in : in STD_LOGIC;
    gt12_txusrclk_in : in STD_LOGIC;
    gt12_txusrclk2_in : in STD_LOGIC;
    gt12_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt12_gthtxn_out : out STD_LOGIC;
    gt12_gthtxp_out : out STD_LOGIC;
    gt12_txoutclk_out : out STD_LOGIC;
    gt12_txoutclkfabric_out : out STD_LOGIC;
    gt12_txoutclkpcs_out : out STD_LOGIC;
    gt12_txresetdone_out : out STD_LOGIC;
    gt12_txpolarity_in : in STD_LOGIC;
    gt12_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt13_cpllfbclklost_out : out STD_LOGIC;
    gt13_cplllock_out : out STD_LOGIC;
    gt13_cplllockdetclk_in : in STD_LOGIC;
    gt13_cpllreset_in : in STD_LOGIC;
    gt13_gtrefclk0_in : in STD_LOGIC;
    gt13_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt13_drpclk_in : in STD_LOGIC;
    gt13_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt13_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt13_drpen_in : in STD_LOGIC;
    gt13_drprdy_out : out STD_LOGIC;
    gt13_drpwe_in : in STD_LOGIC;
    gt13_eyescanreset_in : in STD_LOGIC;
    gt13_rxuserrdy_in : in STD_LOGIC;
    gt13_eyescandataerror_out : out STD_LOGIC;
    gt13_eyescantrigger_in : in STD_LOGIC;
    gt13_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt13_rxusrclk_in : in STD_LOGIC;
    gt13_rxusrclk2_in : in STD_LOGIC;
    gt13_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt13_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt13_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt13_gthrxn_in : in STD_LOGIC;
    gt13_rxbyteisaligned_out : out STD_LOGIC;
    gt13_rxmcommaalignen_in : in STD_LOGIC;
    gt13_rxpcommaalignen_in : in STD_LOGIC;
    gt13_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt13_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt13_gtrxreset_in : in STD_LOGIC;
    gt13_rxpolarity_in : in STD_LOGIC;
    gt13_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt13_gthrxp_in : in STD_LOGIC;
    gt13_rxresetdone_out : out STD_LOGIC;
    gt13_gttxreset_in : in STD_LOGIC;
    gt13_txuserrdy_in : in STD_LOGIC;
    gt13_txusrclk_in : in STD_LOGIC;
    gt13_txusrclk2_in : in STD_LOGIC;
    gt13_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt13_gthtxn_out : out STD_LOGIC;
    gt13_gthtxp_out : out STD_LOGIC;
    gt13_txoutclk_out : out STD_LOGIC;
    gt13_txoutclkfabric_out : out STD_LOGIC;
    gt13_txoutclkpcs_out : out STD_LOGIC;
    gt13_txresetdone_out : out STD_LOGIC;
    gt13_txpolarity_in : in STD_LOGIC;
    gt13_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt14_cpllfbclklost_out : out STD_LOGIC;
    gt14_cplllock_out : out STD_LOGIC;
    gt14_cplllockdetclk_in : in STD_LOGIC;
    gt14_cpllreset_in : in STD_LOGIC;
    gt14_gtrefclk0_in : in STD_LOGIC;
    gt14_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt14_drpclk_in : in STD_LOGIC;
    gt14_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt14_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt14_drpen_in : in STD_LOGIC;
    gt14_drprdy_out : out STD_LOGIC;
    gt14_drpwe_in : in STD_LOGIC;
    gt14_eyescanreset_in : in STD_LOGIC;
    gt14_rxuserrdy_in : in STD_LOGIC;
    gt14_eyescandataerror_out : out STD_LOGIC;
    gt14_eyescantrigger_in : in STD_LOGIC;
    gt14_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt14_rxusrclk_in : in STD_LOGIC;
    gt14_rxusrclk2_in : in STD_LOGIC;
    gt14_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt14_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt14_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt14_gthrxn_in : in STD_LOGIC;
    gt14_rxbyteisaligned_out : out STD_LOGIC;
    gt14_rxmcommaalignen_in : in STD_LOGIC;
    gt14_rxpcommaalignen_in : in STD_LOGIC;
    gt14_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt14_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt14_gtrxreset_in : in STD_LOGIC;
    gt14_rxpolarity_in : in STD_LOGIC;
    gt14_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt14_gthrxp_in : in STD_LOGIC;
    gt14_rxresetdone_out : out STD_LOGIC;
    gt14_gttxreset_in : in STD_LOGIC;
    gt14_txuserrdy_in : in STD_LOGIC;
    gt14_txusrclk_in : in STD_LOGIC;
    gt14_txusrclk2_in : in STD_LOGIC;
    gt14_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt14_gthtxn_out : out STD_LOGIC;
    gt14_gthtxp_out : out STD_LOGIC;
    gt14_txoutclk_out : out STD_LOGIC;
    gt14_txoutclkfabric_out : out STD_LOGIC;
    gt14_txoutclkpcs_out : out STD_LOGIC;
    gt14_txresetdone_out : out STD_LOGIC;
    gt14_txpolarity_in : in STD_LOGIC;
    gt14_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt15_cpllfbclklost_out : out STD_LOGIC;
    gt15_cplllock_out : out STD_LOGIC;
    gt15_cplllockdetclk_in : in STD_LOGIC;
    gt15_cpllreset_in : in STD_LOGIC;
    gt15_gtrefclk0_in : in STD_LOGIC;
    gt15_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt15_drpclk_in : in STD_LOGIC;
    gt15_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt15_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt15_drpen_in : in STD_LOGIC;
    gt15_drprdy_out : out STD_LOGIC;
    gt15_drpwe_in : in STD_LOGIC;
    gt15_eyescanreset_in : in STD_LOGIC;
    gt15_rxuserrdy_in : in STD_LOGIC;
    gt15_eyescandataerror_out : out STD_LOGIC;
    gt15_eyescantrigger_in : in STD_LOGIC;
    gt15_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt15_rxusrclk_in : in STD_LOGIC;
    gt15_rxusrclk2_in : in STD_LOGIC;
    gt15_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt15_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt15_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt15_gthrxn_in : in STD_LOGIC;
    gt15_rxbyteisaligned_out : out STD_LOGIC;
    gt15_rxmcommaalignen_in : in STD_LOGIC;
    gt15_rxpcommaalignen_in : in STD_LOGIC;
    gt15_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt15_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt15_gtrxreset_in : in STD_LOGIC;
    gt15_rxpolarity_in : in STD_LOGIC;
    gt15_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt15_gthrxp_in : in STD_LOGIC;
    gt15_rxresetdone_out : out STD_LOGIC;
    gt15_gttxreset_in : in STD_LOGIC;
    gt15_txuserrdy_in : in STD_LOGIC;
    gt15_txusrclk_in : in STD_LOGIC;
    gt15_txusrclk2_in : in STD_LOGIC;
    gt15_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt15_gthtxn_out : out STD_LOGIC;
    gt15_gthtxp_out : out STD_LOGIC;
    gt15_txoutclk_out : out STD_LOGIC;
    gt15_txoutclkfabric_out : out STD_LOGIC;
    gt15_txoutclkpcs_out : out STD_LOGIC;
    gt15_txresetdone_out : out STD_LOGIC;
    gt15_txpolarity_in : in STD_LOGIC;
    gt15_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt16_cpllfbclklost_out : out STD_LOGIC;
    gt16_cplllock_out : out STD_LOGIC;
    gt16_cplllockdetclk_in : in STD_LOGIC;
    gt16_cpllreset_in : in STD_LOGIC;
    gt16_gtrefclk0_in : in STD_LOGIC;
    gt16_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt16_drpclk_in : in STD_LOGIC;
    gt16_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt16_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt16_drpen_in : in STD_LOGIC;
    gt16_drprdy_out : out STD_LOGIC;
    gt16_drpwe_in : in STD_LOGIC;
    gt16_eyescanreset_in : in STD_LOGIC;
    gt16_rxuserrdy_in : in STD_LOGIC;
    gt16_eyescandataerror_out : out STD_LOGIC;
    gt16_eyescantrigger_in : in STD_LOGIC;
    gt16_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt16_rxusrclk_in : in STD_LOGIC;
    gt16_rxusrclk2_in : in STD_LOGIC;
    gt16_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt16_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt16_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt16_gthrxn_in : in STD_LOGIC;
    gt16_rxbyteisaligned_out : out STD_LOGIC;
    gt16_rxmcommaalignen_in : in STD_LOGIC;
    gt16_rxpcommaalignen_in : in STD_LOGIC;
    gt16_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt16_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt16_gtrxreset_in : in STD_LOGIC;
    gt16_rxpolarity_in : in STD_LOGIC;
    gt16_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt16_gthrxp_in : in STD_LOGIC;
    gt16_rxresetdone_out : out STD_LOGIC;
    gt16_gttxreset_in : in STD_LOGIC;
    gt16_txuserrdy_in : in STD_LOGIC;
    gt16_txusrclk_in : in STD_LOGIC;
    gt16_txusrclk2_in : in STD_LOGIC;
    gt16_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt16_gthtxn_out : out STD_LOGIC;
    gt16_gthtxp_out : out STD_LOGIC;
    gt16_txoutclk_out : out STD_LOGIC;
    gt16_txoutclkfabric_out : out STD_LOGIC;
    gt16_txoutclkpcs_out : out STD_LOGIC;
    gt16_txresetdone_out : out STD_LOGIC;
    gt16_txpolarity_in : in STD_LOGIC;
    gt16_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt17_cpllfbclklost_out : out STD_LOGIC;
    gt17_cplllock_out : out STD_LOGIC;
    gt17_cplllockdetclk_in : in STD_LOGIC;
    gt17_cpllreset_in : in STD_LOGIC;
    gt17_gtrefclk0_in : in STD_LOGIC;
    gt17_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt17_drpclk_in : in STD_LOGIC;
    gt17_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt17_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt17_drpen_in : in STD_LOGIC;
    gt17_drprdy_out : out STD_LOGIC;
    gt17_drpwe_in : in STD_LOGIC;
    gt17_eyescanreset_in : in STD_LOGIC;
    gt17_rxuserrdy_in : in STD_LOGIC;
    gt17_eyescandataerror_out : out STD_LOGIC;
    gt17_eyescantrigger_in : in STD_LOGIC;
    gt17_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt17_rxusrclk_in : in STD_LOGIC;
    gt17_rxusrclk2_in : in STD_LOGIC;
    gt17_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt17_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt17_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt17_gthrxn_in : in STD_LOGIC;
    gt17_rxbyteisaligned_out : out STD_LOGIC;
    gt17_rxmcommaalignen_in : in STD_LOGIC;
    gt17_rxpcommaalignen_in : in STD_LOGIC;
    gt17_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt17_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt17_gtrxreset_in : in STD_LOGIC;
    gt17_rxpolarity_in : in STD_LOGIC;
    gt17_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt17_gthrxp_in : in STD_LOGIC;
    gt17_rxresetdone_out : out STD_LOGIC;
    gt17_gttxreset_in : in STD_LOGIC;
    gt17_txuserrdy_in : in STD_LOGIC;
    gt17_txusrclk_in : in STD_LOGIC;
    gt17_txusrclk2_in : in STD_LOGIC;
    gt17_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt17_gthtxn_out : out STD_LOGIC;
    gt17_gthtxp_out : out STD_LOGIC;
    gt17_txoutclk_out : out STD_LOGIC;
    gt17_txoutclkfabric_out : out STD_LOGIC;
    gt17_txoutclkpcs_out : out STD_LOGIC;
    gt17_txresetdone_out : out STD_LOGIC;
    gt17_txpolarity_in : in STD_LOGIC;
    gt17_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt18_cpllfbclklost_out : out STD_LOGIC;
    gt18_cplllock_out : out STD_LOGIC;
    gt18_cplllockdetclk_in : in STD_LOGIC;
    gt18_cpllreset_in : in STD_LOGIC;
    gt18_gtrefclk0_in : in STD_LOGIC;
    gt18_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt18_drpclk_in : in STD_LOGIC;
    gt18_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt18_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt18_drpen_in : in STD_LOGIC;
    gt18_drprdy_out : out STD_LOGIC;
    gt18_drpwe_in : in STD_LOGIC;
    gt18_eyescanreset_in : in STD_LOGIC;
    gt18_rxuserrdy_in : in STD_LOGIC;
    gt18_eyescandataerror_out : out STD_LOGIC;
    gt18_eyescantrigger_in : in STD_LOGIC;
    gt18_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt18_rxusrclk_in : in STD_LOGIC;
    gt18_rxusrclk2_in : in STD_LOGIC;
    gt18_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt18_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt18_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt18_gthrxn_in : in STD_LOGIC;
    gt18_rxbyteisaligned_out : out STD_LOGIC;
    gt18_rxmcommaalignen_in : in STD_LOGIC;
    gt18_rxpcommaalignen_in : in STD_LOGIC;
    gt18_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt18_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt18_gtrxreset_in : in STD_LOGIC;
    gt18_rxpolarity_in : in STD_LOGIC;
    gt18_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt18_gthrxp_in : in STD_LOGIC;
    gt18_rxresetdone_out : out STD_LOGIC;
    gt18_gttxreset_in : in STD_LOGIC;
    gt18_txuserrdy_in : in STD_LOGIC;
    gt18_txusrclk_in : in STD_LOGIC;
    gt18_txusrclk2_in : in STD_LOGIC;
    gt18_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt18_gthtxn_out : out STD_LOGIC;
    gt18_gthtxp_out : out STD_LOGIC;
    gt18_txoutclk_out : out STD_LOGIC;
    gt18_txoutclkfabric_out : out STD_LOGIC;
    gt18_txoutclkpcs_out : out STD_LOGIC;
    gt18_txresetdone_out : out STD_LOGIC;
    gt18_txpolarity_in : in STD_LOGIC;
    gt18_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    gt19_cpllfbclklost_out : out STD_LOGIC;
    gt19_cplllock_out : out STD_LOGIC;
    gt19_cplllockdetclk_in : in STD_LOGIC;
    gt19_cpllreset_in : in STD_LOGIC;
    gt19_gtrefclk0_in : in STD_LOGIC;
    gt19_drpaddr_in : in STD_LOGIC_VECTOR ( 8 downto 0 );
    gt19_drpclk_in : in STD_LOGIC;
    gt19_drpdi_in : in STD_LOGIC_VECTOR ( 15 downto 0 );
    gt19_drpdo_out : out STD_LOGIC_VECTOR ( 15 downto 0 );
    gt19_drpen_in : in STD_LOGIC;
    gt19_drprdy_out : out STD_LOGIC;
    gt19_drpwe_in : in STD_LOGIC;
    gt19_eyescanreset_in : in STD_LOGIC;
    gt19_rxuserrdy_in : in STD_LOGIC;
    gt19_eyescandataerror_out : out STD_LOGIC;
    gt19_eyescantrigger_in : in STD_LOGIC;
    gt19_dmonitorout_out : out STD_LOGIC_VECTOR ( 14 downto 0 );
    gt19_rxusrclk_in : in STD_LOGIC;
    gt19_rxusrclk2_in : in STD_LOGIC;
    gt19_rxdata_out : out STD_LOGIC_VECTOR ( 31 downto 0 );
    gt19_rxdisperr_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt19_rxnotintable_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt19_gthrxn_in : in STD_LOGIC;
    gt19_rxbyteisaligned_out : out STD_LOGIC;
    gt19_rxmcommaalignen_in : in STD_LOGIC;
    gt19_rxpcommaalignen_in : in STD_LOGIC;
    gt19_rxmonitorout_out : out STD_LOGIC_VECTOR ( 6 downto 0 );
    gt19_rxmonitorsel_in : in STD_LOGIC_VECTOR ( 1 downto 0 );
    gt19_gtrxreset_in : in STD_LOGIC;
    gt19_rxpolarity_in : in STD_LOGIC;
    gt19_rxcharisk_out : out STD_LOGIC_VECTOR ( 3 downto 0 );
    gt19_gthrxp_in : in STD_LOGIC;
    gt19_rxresetdone_out : out STD_LOGIC;
    gt19_gttxreset_in : in STD_LOGIC;
    gt19_txuserrdy_in : in STD_LOGIC;
    gt19_txusrclk_in : in STD_LOGIC;
    gt19_txusrclk2_in : in STD_LOGIC;
    gt19_txdata_in : in STD_LOGIC_VECTOR ( 31 downto 0 );
    gt19_gthtxn_out : out STD_LOGIC;
    gt19_gthtxp_out : out STD_LOGIC;
    gt19_txoutclk_out : out STD_LOGIC;
    gt19_txoutclkfabric_out : out STD_LOGIC;
    gt19_txoutclkpcs_out : out STD_LOGIC;
    gt19_txresetdone_out : out STD_LOGIC;
    gt19_txpolarity_in : in STD_LOGIC;
    gt19_txcharisk_in : in STD_LOGIC_VECTOR ( 3 downto 0 );
    GT0_QPLLOUTCLK_IN : in STD_LOGIC;
    GT0_QPLLOUTREFCLK_IN : in STD_LOGIC;
    GT1_QPLLOUTCLK_IN : in STD_LOGIC;
    GT1_QPLLOUTREFCLK_IN : in STD_LOGIC;
    GT2_QPLLOUTCLK_IN : in STD_LOGIC;
    GT2_QPLLOUTREFCLK_IN : in STD_LOGIC;
    GT3_QPLLOUTCLK_IN : in STD_LOGIC;
    GT3_QPLLOUTREFCLK_IN : in STD_LOGIC;
    GT4_QPLLOUTCLK_IN : in STD_LOGIC;
    GT4_QPLLOUTREFCLK_IN : in STD_LOGIC
  );

end gt625_fab20;

architecture stub of gt625_fab20 is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "SYSCLK_IN,SOFT_RESET_IN,DONT_RESET_ON_DATA_ERROR_IN,GT0_TX_FSM_RESET_DONE_OUT,GT0_RX_FSM_RESET_DONE_OUT,GT0_DATA_VALID_IN,GT1_TX_FSM_RESET_DONE_OUT,GT1_RX_FSM_RESET_DONE_OUT,GT1_DATA_VALID_IN,GT2_TX_FSM_RESET_DONE_OUT,GT2_RX_FSM_RESET_DONE_OUT,GT2_DATA_VALID_IN,GT3_TX_FSM_RESET_DONE_OUT,GT3_RX_FSM_RESET_DONE_OUT,GT3_DATA_VALID_IN,GT4_TX_FSM_RESET_DONE_OUT,GT4_RX_FSM_RESET_DONE_OUT,GT4_DATA_VALID_IN,GT5_TX_FSM_RESET_DONE_OUT,GT5_RX_FSM_RESET_DONE_OUT,GT5_DATA_VALID_IN,GT6_TX_FSM_RESET_DONE_OUT,GT6_RX_FSM_RESET_DONE_OUT,GT6_DATA_VALID_IN,GT7_TX_FSM_RESET_DONE_OUT,GT7_RX_FSM_RESET_DONE_OUT,GT7_DATA_VALID_IN,GT8_TX_FSM_RESET_DONE_OUT,GT8_RX_FSM_RESET_DONE_OUT,GT8_DATA_VALID_IN,GT9_TX_FSM_RESET_DONE_OUT,GT9_RX_FSM_RESET_DONE_OUT,GT9_DATA_VALID_IN,GT10_TX_FSM_RESET_DONE_OUT,GT10_RX_FSM_RESET_DONE_OUT,GT10_DATA_VALID_IN,GT11_TX_FSM_RESET_DONE_OUT,GT11_RX_FSM_RESET_DONE_OUT,GT11_DATA_VALID_IN,GT12_TX_FSM_RESET_DONE_OUT,GT12_RX_FSM_RESET_DONE_OUT,GT12_DATA_VALID_IN,GT13_TX_FSM_RESET_DONE_OUT,GT13_RX_FSM_RESET_DONE_OUT,GT13_DATA_VALID_IN,GT14_TX_FSM_RESET_DONE_OUT,GT14_RX_FSM_RESET_DONE_OUT,GT14_DATA_VALID_IN,GT15_TX_FSM_RESET_DONE_OUT,GT15_RX_FSM_RESET_DONE_OUT,GT15_DATA_VALID_IN,GT16_TX_FSM_RESET_DONE_OUT,GT16_RX_FSM_RESET_DONE_OUT,GT16_DATA_VALID_IN,GT17_TX_FSM_RESET_DONE_OUT,GT17_RX_FSM_RESET_DONE_OUT,GT17_DATA_VALID_IN,GT18_TX_FSM_RESET_DONE_OUT,GT18_RX_FSM_RESET_DONE_OUT,GT18_DATA_VALID_IN,GT19_TX_FSM_RESET_DONE_OUT,GT19_RX_FSM_RESET_DONE_OUT,GT19_DATA_VALID_IN,gt0_cpllfbclklost_out,gt0_cplllock_out,gt0_cplllockdetclk_in,gt0_cpllreset_in,gt0_gtrefclk0_in,gt0_drpaddr_in[8:0],gt0_drpclk_in,gt0_drpdi_in[15:0],gt0_drpdo_out[15:0],gt0_drpen_in,gt0_drprdy_out,gt0_drpwe_in,gt0_eyescanreset_in,gt0_rxuserrdy_in,gt0_eyescandataerror_out,gt0_eyescantrigger_in,gt0_dmonitorout_out[14:0],gt0_rxusrclk_in,gt0_rxusrclk2_in,gt0_rxdata_out[31:0],gt0_rxdisperr_out[3:0],gt0_rxnotintable_out[3:0],gt0_gthrxn_in,gt0_rxbyteisaligned_out,gt0_rxmcommaalignen_in,gt0_rxpcommaalignen_in,gt0_rxmonitorout_out[6:0],gt0_rxmonitorsel_in[1:0],gt0_gtrxreset_in,gt0_rxpolarity_in,gt0_rxcharisk_out[3:0],gt0_gthrxp_in,gt0_rxresetdone_out,gt0_gttxreset_in,gt0_txuserrdy_in,gt0_txusrclk_in,gt0_txusrclk2_in,gt0_txdata_in[31:0],gt0_gthtxn_out,gt0_gthtxp_out,gt0_txoutclk_out,gt0_txoutclkfabric_out,gt0_txoutclkpcs_out,gt0_txresetdone_out,gt0_txpolarity_in,gt0_txcharisk_in[3:0],gt1_cpllfbclklost_out,gt1_cplllock_out,gt1_cplllockdetclk_in,gt1_cpllreset_in,gt1_gtrefclk0_in,gt1_drpaddr_in[8:0],gt1_drpclk_in,gt1_drpdi_in[15:0],gt1_drpdo_out[15:0],gt1_drpen_in,gt1_drprdy_out,gt1_drpwe_in,gt1_eyescanreset_in,gt1_rxuserrdy_in,gt1_eyescandataerror_out,gt1_eyescantrigger_in,gt1_dmonitorout_out[14:0],gt1_rxusrclk_in,gt1_rxusrclk2_in,gt1_rxdata_out[31:0],gt1_rxdisperr_out[3:0],gt1_rxnotintable_out[3:0],gt1_gthrxn_in,gt1_rxbyteisaligned_out,gt1_rxmcommaalignen_in,gt1_rxpcommaalignen_in,gt1_rxmonitorout_out[6:0],gt1_rxmonitorsel_in[1:0],gt1_gtrxreset_in,gt1_rxpolarity_in,gt1_rxcharisk_out[3:0],gt1_gthrxp_in,gt1_rxresetdone_out,gt1_gttxreset_in,gt1_txuserrdy_in,gt1_txusrclk_in,gt1_txusrclk2_in,gt1_txdata_in[31:0],gt1_gthtxn_out,gt1_gthtxp_out,gt1_txoutclk_out,gt1_txoutclkfabric_out,gt1_txoutclkpcs_out,gt1_txresetdone_out,gt1_txpolarity_in,gt1_txcharisk_in[3:0],gt2_cpllfbclklost_out,gt2_cplllock_out,gt2_cplllockdetclk_in,gt2_cpllreset_in,gt2_gtrefclk0_in,gt2_drpaddr_in[8:0],gt2_drpclk_in,gt2_drpdi_in[15:0],gt2_drpdo_out[15:0],gt2_drpen_in,gt2_drprdy_out,gt2_drpwe_in,gt2_eyescanreset_in,gt2_rxuserrdy_in,gt2_eyescandataerror_out,gt2_eyescantrigger_in,gt2_dmonitorout_out[14:0],gt2_rxusrclk_in,gt2_rxusrclk2_in,gt2_rxdata_out[31:0],gt2_rxdisperr_out[3:0],gt2_rxnotintable_out[3:0],gt2_gthrxn_in,gt2_rxbyteisaligned_out,gt2_rxmcommaalignen_in,gt2_rxpcommaalignen_in,gt2_rxmonitorout_out[6:0],gt2_rxmonitorsel_in[1:0],gt2_gtrxreset_in,gt2_rxpolarity_in,gt2_rxcharisk_out[3:0],gt2_gthrxp_in,gt2_rxresetdone_out,gt2_gttxreset_in,gt2_txuserrdy_in,gt2_txusrclk_in,gt2_txusrclk2_in,gt2_txdata_in[31:0],gt2_gthtxn_out,gt2_gthtxp_out,gt2_txoutclk_out,gt2_txoutclkfabric_out,gt2_txoutclkpcs_out,gt2_txresetdone_out,gt2_txpolarity_in,gt2_txcharisk_in[3:0],gt3_cpllfbclklost_out,gt3_cplllock_out,gt3_cplllockdetclk_in,gt3_cpllreset_in,gt3_gtrefclk0_in,gt3_drpaddr_in[8:0],gt3_drpclk_in,gt3_drpdi_in[15:0],gt3_drpdo_out[15:0],gt3_drpen_in,gt3_drprdy_out,gt3_drpwe_in,gt3_eyescanreset_in,gt3_rxuserrdy_in,gt3_eyescandataerror_out,gt3_eyescantrigger_in,gt3_dmonitorout_out[14:0],gt3_rxusrclk_in,gt3_rxusrclk2_in,gt3_rxdata_out[31:0],gt3_rxdisperr_out[3:0],gt3_rxnotintable_out[3:0],gt3_gthrxn_in,gt3_rxbyteisaligned_out,gt3_rxmcommaalignen_in,gt3_rxpcommaalignen_in,gt3_rxmonitorout_out[6:0],gt3_rxmonitorsel_in[1:0],gt3_gtrxreset_in,gt3_rxpolarity_in,gt3_rxcharisk_out[3:0],gt3_gthrxp_in,gt3_rxresetdone_out,gt3_gttxreset_in,gt3_txuserrdy_in,gt3_txusrclk_in,gt3_txusrclk2_in,gt3_txdata_in[31:0],gt3_gthtxn_out,gt3_gthtxp_out,gt3_txoutclk_out,gt3_txoutclkfabric_out,gt3_txoutclkpcs_out,gt3_txresetdone_out,gt3_txpolarity_in,gt3_txcharisk_in[3:0],gt4_cpllfbclklost_out,gt4_cplllock_out,gt4_cplllockdetclk_in,gt4_cpllreset_in,gt4_gtrefclk0_in,gt4_drpaddr_in[8:0],gt4_drpclk_in,gt4_drpdi_in[15:0],gt4_drpdo_out[15:0],gt4_drpen_in,gt4_drprdy_out,gt4_drpwe_in,gt4_eyescanreset_in,gt4_rxuserrdy_in,gt4_eyescandataerror_out,gt4_eyescantrigger_in,gt4_dmonitorout_out[14:0],gt4_rxusrclk_in,gt4_rxusrclk2_in,gt4_rxdata_out[31:0],gt4_rxdisperr_out[3:0],gt4_rxnotintable_out[3:0],gt4_gthrxn_in,gt4_rxbyteisaligned_out,gt4_rxmcommaalignen_in,gt4_rxpcommaalignen_in,gt4_rxmonitorout_out[6:0],gt4_rxmonitorsel_in[1:0],gt4_gtrxreset_in,gt4_rxpolarity_in,gt4_rxcharisk_out[3:0],gt4_gthrxp_in,gt4_rxresetdone_out,gt4_gttxreset_in,gt4_txuserrdy_in,gt4_txusrclk_in,gt4_txusrclk2_in,gt4_txdata_in[31:0],gt4_gthtxn_out,gt4_gthtxp_out,gt4_txoutclk_out,gt4_txoutclkfabric_out,gt4_txoutclkpcs_out,gt4_txresetdone_out,gt4_txpolarity_in,gt4_txcharisk_in[3:0],gt5_cpllfbclklost_out,gt5_cplllock_out,gt5_cplllockdetclk_in,gt5_cpllreset_in,gt5_gtrefclk0_in,gt5_drpaddr_in[8:0],gt5_drpclk_in,gt5_drpdi_in[15:0],gt5_drpdo_out[15:0],gt5_drpen_in,gt5_drprdy_out,gt5_drpwe_in,gt5_eyescanreset_in,gt5_rxuserrdy_in,gt5_eyescandataerror_out,gt5_eyescantrigger_in,gt5_dmonitorout_out[14:0],gt5_rxusrclk_in,gt5_rxusrclk2_in,gt5_rxdata_out[31:0],gt5_rxdisperr_out[3:0],gt5_rxnotintable_out[3:0],gt5_gthrxn_in,gt5_rxbyteisaligned_out,gt5_rxmcommaalignen_in,gt5_rxpcommaalignen_in,gt5_rxmonitorout_out[6:0],gt5_rxmonitorsel_in[1:0],gt5_gtrxreset_in,gt5_rxpolarity_in,gt5_rxcharisk_out[3:0],gt5_gthrxp_in,gt5_rxresetdone_out,gt5_gttxreset_in,gt5_txuserrdy_in,gt5_txusrclk_in,gt5_txusrclk2_in,gt5_txdata_in[31:0],gt5_gthtxn_out,gt5_gthtxp_out,gt5_txoutclk_out,gt5_txoutclkfabric_out,gt5_txoutclkpcs_out,gt5_txresetdone_out,gt5_txpolarity_in,gt5_txcharisk_in[3:0],gt6_cpllfbclklost_out,gt6_cplllock_out,gt6_cplllockdetclk_in,gt6_cpllreset_in,gt6_gtrefclk0_in,gt6_drpaddr_in[8:0],gt6_drpclk_in,gt6_drpdi_in[15:0],gt6_drpdo_out[15:0],gt6_drpen_in,gt6_drprdy_out,gt6_drpwe_in,gt6_eyescanreset_in,gt6_rxuserrdy_in,gt6_eyescandataerror_out,gt6_eyescantrigger_in,gt6_dmonitorout_out[14:0],gt6_rxusrclk_in,gt6_rxusrclk2_in,gt6_rxdata_out[31:0],gt6_rxdisperr_out[3:0],gt6_rxnotintable_out[3:0],gt6_gthrxn_in,gt6_rxbyteisaligned_out,gt6_rxmcommaalignen_in,gt6_rxpcommaalignen_in,gt6_rxmonitorout_out[6:0],gt6_rxmonitorsel_in[1:0],gt6_gtrxreset_in,gt6_rxpolarity_in,gt6_rxcharisk_out[3:0],gt6_gthrxp_in,gt6_rxresetdone_out,gt6_gttxreset_in,gt6_txuserrdy_in,gt6_txusrclk_in,gt6_txusrclk2_in,gt6_txdata_in[31:0],gt6_gthtxn_out,gt6_gthtxp_out,gt6_txoutclk_out,gt6_txoutclkfabric_out,gt6_txoutclkpcs_out,gt6_txresetdone_out,gt6_txpolarity_in,gt6_txcharisk_in[3:0],gt7_cpllfbclklost_out,gt7_cplllock_out,gt7_cplllockdetclk_in,gt7_cpllreset_in,gt7_gtrefclk0_in,gt7_drpaddr_in[8:0],gt7_drpclk_in,gt7_drpdi_in[15:0],gt7_drpdo_out[15:0],gt7_drpen_in,gt7_drprdy_out,gt7_drpwe_in,gt7_eyescanreset_in,gt7_rxuserrdy_in,gt7_eyescandataerror_out,gt7_eyescantrigger_in,gt7_dmonitorout_out[14:0],gt7_rxusrclk_in,gt7_rxusrclk2_in,gt7_rxdata_out[31:0],gt7_rxdisperr_out[3:0],gt7_rxnotintable_out[3:0],gt7_gthrxn_in,gt7_rxbyteisaligned_out,gt7_rxmcommaalignen_in,gt7_rxpcommaalignen_in,gt7_rxmonitorout_out[6:0],gt7_rxmonitorsel_in[1:0],gt7_gtrxreset_in,gt7_rxpolarity_in,gt7_rxcharisk_out[3:0],gt7_gthrxp_in,gt7_rxresetdone_out,gt7_gttxreset_in,gt7_txuserrdy_in,gt7_txusrclk_in,gt7_txusrclk2_in,gt7_txdata_in[31:0],gt7_gthtxn_out,gt7_gthtxp_out,gt7_txoutclk_out,gt7_txoutclkfabric_out,gt7_txoutclkpcs_out,gt7_txresetdone_out,gt7_txpolarity_in,gt7_txcharisk_in[3:0],gt8_cpllfbclklost_out,gt8_cplllock_out,gt8_cplllockdetclk_in,gt8_cpllreset_in,gt8_gtrefclk0_in,gt8_drpaddr_in[8:0],gt8_drpclk_in,gt8_drpdi_in[15:0],gt8_drpdo_out[15:0],gt8_drpen_in,gt8_drprdy_out,gt8_drpwe_in,gt8_eyescanreset_in,gt8_rxuserrdy_in,gt8_eyescandataerror_out,gt8_eyescantrigger_in,gt8_dmonitorout_out[14:0],gt8_rxusrclk_in,gt8_rxusrclk2_in,gt8_rxdata_out[31:0],gt8_rxdisperr_out[3:0],gt8_rxnotintable_out[3:0],gt8_gthrxn_in,gt8_rxbyteisaligned_out,gt8_rxmcommaalignen_in,gt8_rxpcommaalignen_in,gt8_rxmonitorout_out[6:0],gt8_rxmonitorsel_in[1:0],gt8_gtrxreset_in,gt8_rxpolarity_in,gt8_rxcharisk_out[3:0],gt8_gthrxp_in,gt8_rxresetdone_out,gt8_gttxreset_in,gt8_txuserrdy_in,gt8_txusrclk_in,gt8_txusrclk2_in,gt8_txdata_in[31:0],gt8_gthtxn_out,gt8_gthtxp_out,gt8_txoutclk_out,gt8_txoutclkfabric_out,gt8_txoutclkpcs_out,gt8_txresetdone_out,gt8_txpolarity_in,gt8_txcharisk_in[3:0],gt9_cpllfbclklost_out,gt9_cplllock_out,gt9_cplllockdetclk_in,gt9_cpllreset_in,gt9_gtrefclk0_in,gt9_drpaddr_in[8:0],gt9_drpclk_in,gt9_drpdi_in[15:0],gt9_drpdo_out[15:0],gt9_drpen_in,gt9_drprdy_out,gt9_drpwe_in,gt9_eyescanreset_in,gt9_rxuserrdy_in,gt9_eyescandataerror_out,gt9_eyescantrigger_in,gt9_dmonitorout_out[14:0],gt9_rxusrclk_in,gt9_rxusrclk2_in,gt9_rxdata_out[31:0],gt9_rxdisperr_out[3:0],gt9_rxnotintable_out[3:0],gt9_gthrxn_in,gt9_rxbyteisaligned_out,gt9_rxmcommaalignen_in,gt9_rxpcommaalignen_in,gt9_rxmonitorout_out[6:0],gt9_rxmonitorsel_in[1:0],gt9_gtrxreset_in,gt9_rxpolarity_in,gt9_rxcharisk_out[3:0],gt9_gthrxp_in,gt9_rxresetdone_out,gt9_gttxreset_in,gt9_txuserrdy_in,gt9_txusrclk_in,gt9_txusrclk2_in,gt9_txdata_in[31:0],gt9_gthtxn_out,gt9_gthtxp_out,gt9_txoutclk_out,gt9_txoutclkfabric_out,gt9_txoutclkpcs_out,gt9_txresetdone_out,gt9_txpolarity_in,gt9_txcharisk_in[3:0],gt10_cpllfbclklost_out,gt10_cplllock_out,gt10_cplllockdetclk_in,gt10_cpllreset_in,gt10_gtrefclk0_in,gt10_drpaddr_in[8:0],gt10_drpclk_in,gt10_drpdi_in[15:0],gt10_drpdo_out[15:0],gt10_drpen_in,gt10_drprdy_out,gt10_drpwe_in,gt10_eyescanreset_in,gt10_rxuserrdy_in,gt10_eyescandataerror_out,gt10_eyescantrigger_in,gt10_dmonitorout_out[14:0],gt10_rxusrclk_in,gt10_rxusrclk2_in,gt10_rxdata_out[31:0],gt10_rxdisperr_out[3:0],gt10_rxnotintable_out[3:0],gt10_gthrxn_in,gt10_rxbyteisaligned_out,gt10_rxmcommaalignen_in,gt10_rxpcommaalignen_in,gt10_rxmonitorout_out[6:0],gt10_rxmonitorsel_in[1:0],gt10_gtrxreset_in,gt10_rxpolarity_in,gt10_rxcharisk_out[3:0],gt10_gthrxp_in,gt10_rxresetdone_out,gt10_gttxreset_in,gt10_txuserrdy_in,gt10_txusrclk_in,gt10_txusrclk2_in,gt10_txdata_in[31:0],gt10_gthtxn_out,gt10_gthtxp_out,gt10_txoutclk_out,gt10_txoutclkfabric_out,gt10_txoutclkpcs_out,gt10_txresetdone_out,gt10_txpolarity_in,gt10_txcharisk_in[3:0],gt11_cpllfbclklost_out,gt11_cplllock_out,gt11_cplllockdetclk_in,gt11_cpllreset_in,gt11_gtrefclk0_in,gt11_drpaddr_in[8:0],gt11_drpclk_in,gt11_drpdi_in[15:0],gt11_drpdo_out[15:0],gt11_drpen_in,gt11_drprdy_out,gt11_drpwe_in,gt11_eyescanreset_in,gt11_rxuserrdy_in,gt11_eyescandataerror_out,gt11_eyescantrigger_in,gt11_dmonitorout_out[14:0],gt11_rxusrclk_in,gt11_rxusrclk2_in,gt11_rxdata_out[31:0],gt11_rxdisperr_out[3:0],gt11_rxnotintable_out[3:0],gt11_gthrxn_in,gt11_rxbyteisaligned_out,gt11_rxmcommaalignen_in,gt11_rxpcommaalignen_in,gt11_rxmonitorout_out[6:0],gt11_rxmonitorsel_in[1:0],gt11_gtrxreset_in,gt11_rxpolarity_in,gt11_rxcharisk_out[3:0],gt11_gthrxp_in,gt11_rxresetdone_out,gt11_gttxreset_in,gt11_txuserrdy_in,gt11_txusrclk_in,gt11_txusrclk2_in,gt11_txdata_in[31:0],gt11_gthtxn_out,gt11_gthtxp_out,gt11_txoutclk_out,gt11_txoutclkfabric_out,gt11_txoutclkpcs_out,gt11_txresetdone_out,gt11_txpolarity_in,gt11_txcharisk_in[3:0],gt12_cpllfbclklost_out,gt12_cplllock_out,gt12_cplllockdetclk_in,gt12_cpllreset_in,gt12_gtrefclk0_in,gt12_drpaddr_in[8:0],gt12_drpclk_in,gt12_drpdi_in[15:0],gt12_drpdo_out[15:0],gt12_drpen_in,gt12_drprdy_out,gt12_drpwe_in,gt12_eyescanreset_in,gt12_rxuserrdy_in,gt12_eyescandataerror_out,gt12_eyescantrigger_in,gt12_dmonitorout_out[14:0],gt12_rxusrclk_in,gt12_rxusrclk2_in,gt12_rxdata_out[31:0],gt12_rxdisperr_out[3:0],gt12_rxnotintable_out[3:0],gt12_gthrxn_in,gt12_rxbyteisaligned_out,gt12_rxmcommaalignen_in,gt12_rxpcommaalignen_in,gt12_rxmonitorout_out[6:0],gt12_rxmonitorsel_in[1:0],gt12_gtrxreset_in,gt12_rxpolarity_in,gt12_rxcharisk_out[3:0],gt12_gthrxp_in,gt12_rxresetdone_out,gt12_gttxreset_in,gt12_txuserrdy_in,gt12_txusrclk_in,gt12_txusrclk2_in,gt12_txdata_in[31:0],gt12_gthtxn_out,gt12_gthtxp_out,gt12_txoutclk_out,gt12_txoutclkfabric_out,gt12_txoutclkpcs_out,gt12_txresetdone_out,gt12_txpolarity_in,gt12_txcharisk_in[3:0],gt13_cpllfbclklost_out,gt13_cplllock_out,gt13_cplllockdetclk_in,gt13_cpllreset_in,gt13_gtrefclk0_in,gt13_drpaddr_in[8:0],gt13_drpclk_in,gt13_drpdi_in[15:0],gt13_drpdo_out[15:0],gt13_drpen_in,gt13_drprdy_out,gt13_drpwe_in,gt13_eyescanreset_in,gt13_rxuserrdy_in,gt13_eyescandataerror_out,gt13_eyescantrigger_in,gt13_dmonitorout_out[14:0],gt13_rxusrclk_in,gt13_rxusrclk2_in,gt13_rxdata_out[31:0],gt13_rxdisperr_out[3:0],gt13_rxnotintable_out[3:0],gt13_gthrxn_in,gt13_rxbyteisaligned_out,gt13_rxmcommaalignen_in,gt13_rxpcommaalignen_in,gt13_rxmonitorout_out[6:0],gt13_rxmonitorsel_in[1:0],gt13_gtrxreset_in,gt13_rxpolarity_in,gt13_rxcharisk_out[3:0],gt13_gthrxp_in,gt13_rxresetdone_out,gt13_gttxreset_in,gt13_txuserrdy_in,gt13_txusrclk_in,gt13_txusrclk2_in,gt13_txdata_in[31:0],gt13_gthtxn_out,gt13_gthtxp_out,gt13_txoutclk_out,gt13_txoutclkfabric_out,gt13_txoutclkpcs_out,gt13_txresetdone_out,gt13_txpolarity_in,gt13_txcharisk_in[3:0],gt14_cpllfbclklost_out,gt14_cplllock_out,gt14_cplllockdetclk_in,gt14_cpllreset_in,gt14_gtrefclk0_in,gt14_drpaddr_in[8:0],gt14_drpclk_in,gt14_drpdi_in[15:0],gt14_drpdo_out[15:0],gt14_drpen_in,gt14_drprdy_out,gt14_drpwe_in,gt14_eyescanreset_in,gt14_rxuserrdy_in,gt14_eyescandataerror_out,gt14_eyescantrigger_in,gt14_dmonitorout_out[14:0],gt14_rxusrclk_in,gt14_rxusrclk2_in,gt14_rxdata_out[31:0],gt14_rxdisperr_out[3:0],gt14_rxnotintable_out[3:0],gt14_gthrxn_in,gt14_rxbyteisaligned_out,gt14_rxmcommaalignen_in,gt14_rxpcommaalignen_in,gt14_rxmonitorout_out[6:0],gt14_rxmonitorsel_in[1:0],gt14_gtrxreset_in,gt14_rxpolarity_in,gt14_rxcharisk_out[3:0],gt14_gthrxp_in,gt14_rxresetdone_out,gt14_gttxreset_in,gt14_txuserrdy_in,gt14_txusrclk_in,gt14_txusrclk2_in,gt14_txdata_in[31:0],gt14_gthtxn_out,gt14_gthtxp_out,gt14_txoutclk_out,gt14_txoutclkfabric_out,gt14_txoutclkpcs_out,gt14_txresetdone_out,gt14_txpolarity_in,gt14_txcharisk_in[3:0],gt15_cpllfbclklost_out,gt15_cplllock_out,gt15_cplllockdetclk_in,gt15_cpllreset_in,gt15_gtrefclk0_in,gt15_drpaddr_in[8:0],gt15_drpclk_in,gt15_drpdi_in[15:0],gt15_drpdo_out[15:0],gt15_drpen_in,gt15_drprdy_out,gt15_drpwe_in,gt15_eyescanreset_in,gt15_rxuserrdy_in,gt15_eyescandataerror_out,gt15_eyescantrigger_in,gt15_dmonitorout_out[14:0],gt15_rxusrclk_in,gt15_rxusrclk2_in,gt15_rxdata_out[31:0],gt15_rxdisperr_out[3:0],gt15_rxnotintable_out[3:0],gt15_gthrxn_in,gt15_rxbyteisaligned_out,gt15_rxmcommaalignen_in,gt15_rxpcommaalignen_in,gt15_rxmonitorout_out[6:0],gt15_rxmonitorsel_in[1:0],gt15_gtrxreset_in,gt15_rxpolarity_in,gt15_rxcharisk_out[3:0],gt15_gthrxp_in,gt15_rxresetdone_out,gt15_gttxreset_in,gt15_txuserrdy_in,gt15_txusrclk_in,gt15_txusrclk2_in,gt15_txdata_in[31:0],gt15_gthtxn_out,gt15_gthtxp_out,gt15_txoutclk_out,gt15_txoutclkfabric_out,gt15_txoutclkpcs_out,gt15_txresetdone_out,gt15_txpolarity_in,gt15_txcharisk_in[3:0],gt16_cpllfbclklost_out,gt16_cplllock_out,gt16_cplllockdetclk_in,gt16_cpllreset_in,gt16_gtrefclk0_in,gt16_drpaddr_in[8:0],gt16_drpclk_in,gt16_drpdi_in[15:0],gt16_drpdo_out[15:0],gt16_drpen_in,gt16_drprdy_out,gt16_drpwe_in,gt16_eyescanreset_in,gt16_rxuserrdy_in,gt16_eyescandataerror_out,gt16_eyescantrigger_in,gt16_dmonitorout_out[14:0],gt16_rxusrclk_in,gt16_rxusrclk2_in,gt16_rxdata_out[31:0],gt16_rxdisperr_out[3:0],gt16_rxnotintable_out[3:0],gt16_gthrxn_in,gt16_rxbyteisaligned_out,gt16_rxmcommaalignen_in,gt16_rxpcommaalignen_in,gt16_rxmonitorout_out[6:0],gt16_rxmonitorsel_in[1:0],gt16_gtrxreset_in,gt16_rxpolarity_in,gt16_rxcharisk_out[3:0],gt16_gthrxp_in,gt16_rxresetdone_out,gt16_gttxreset_in,gt16_txuserrdy_in,gt16_txusrclk_in,gt16_txusrclk2_in,gt16_txdata_in[31:0],gt16_gthtxn_out,gt16_gthtxp_out,gt16_txoutclk_out,gt16_txoutclkfabric_out,gt16_txoutclkpcs_out,gt16_txresetdone_out,gt16_txpolarity_in,gt16_txcharisk_in[3:0],gt17_cpllfbclklost_out,gt17_cplllock_out,gt17_cplllockdetclk_in,gt17_cpllreset_in,gt17_gtrefclk0_in,gt17_drpaddr_in[8:0],gt17_drpclk_in,gt17_drpdi_in[15:0],gt17_drpdo_out[15:0],gt17_drpen_in,gt17_drprdy_out,gt17_drpwe_in,gt17_eyescanreset_in,gt17_rxuserrdy_in,gt17_eyescandataerror_out,gt17_eyescantrigger_in,gt17_dmonitorout_out[14:0],gt17_rxusrclk_in,gt17_rxusrclk2_in,gt17_rxdata_out[31:0],gt17_rxdisperr_out[3:0],gt17_rxnotintable_out[3:0],gt17_gthrxn_in,gt17_rxbyteisaligned_out,gt17_rxmcommaalignen_in,gt17_rxpcommaalignen_in,gt17_rxmonitorout_out[6:0],gt17_rxmonitorsel_in[1:0],gt17_gtrxreset_in,gt17_rxpolarity_in,gt17_rxcharisk_out[3:0],gt17_gthrxp_in,gt17_rxresetdone_out,gt17_gttxreset_in,gt17_txuserrdy_in,gt17_txusrclk_in,gt17_txusrclk2_in,gt17_txdata_in[31:0],gt17_gthtxn_out,gt17_gthtxp_out,gt17_txoutclk_out,gt17_txoutclkfabric_out,gt17_txoutclkpcs_out,gt17_txresetdone_out,gt17_txpolarity_in,gt17_txcharisk_in[3:0],gt18_cpllfbclklost_out,gt18_cplllock_out,gt18_cplllockdetclk_in,gt18_cpllreset_in,gt18_gtrefclk0_in,gt18_drpaddr_in[8:0],gt18_drpclk_in,gt18_drpdi_in[15:0],gt18_drpdo_out[15:0],gt18_drpen_in,gt18_drprdy_out,gt18_drpwe_in,gt18_eyescanreset_in,gt18_rxuserrdy_in,gt18_eyescandataerror_out,gt18_eyescantrigger_in,gt18_dmonitorout_out[14:0],gt18_rxusrclk_in,gt18_rxusrclk2_in,gt18_rxdata_out[31:0],gt18_rxdisperr_out[3:0],gt18_rxnotintable_out[3:0],gt18_gthrxn_in,gt18_rxbyteisaligned_out,gt18_rxmcommaalignen_in,gt18_rxpcommaalignen_in,gt18_rxmonitorout_out[6:0],gt18_rxmonitorsel_in[1:0],gt18_gtrxreset_in,gt18_rxpolarity_in,gt18_rxcharisk_out[3:0],gt18_gthrxp_in,gt18_rxresetdone_out,gt18_gttxreset_in,gt18_txuserrdy_in,gt18_txusrclk_in,gt18_txusrclk2_in,gt18_txdata_in[31:0],gt18_gthtxn_out,gt18_gthtxp_out,gt18_txoutclk_out,gt18_txoutclkfabric_out,gt18_txoutclkpcs_out,gt18_txresetdone_out,gt18_txpolarity_in,gt18_txcharisk_in[3:0],gt19_cpllfbclklost_out,gt19_cplllock_out,gt19_cplllockdetclk_in,gt19_cpllreset_in,gt19_gtrefclk0_in,gt19_drpaddr_in[8:0],gt19_drpclk_in,gt19_drpdi_in[15:0],gt19_drpdo_out[15:0],gt19_drpen_in,gt19_drprdy_out,gt19_drpwe_in,gt19_eyescanreset_in,gt19_rxuserrdy_in,gt19_eyescandataerror_out,gt19_eyescantrigger_in,gt19_dmonitorout_out[14:0],gt19_rxusrclk_in,gt19_rxusrclk2_in,gt19_rxdata_out[31:0],gt19_rxdisperr_out[3:0],gt19_rxnotintable_out[3:0],gt19_gthrxn_in,gt19_rxbyteisaligned_out,gt19_rxmcommaalignen_in,gt19_rxpcommaalignen_in,gt19_rxmonitorout_out[6:0],gt19_rxmonitorsel_in[1:0],gt19_gtrxreset_in,gt19_rxpolarity_in,gt19_rxcharisk_out[3:0],gt19_gthrxp_in,gt19_rxresetdone_out,gt19_gttxreset_in,gt19_txuserrdy_in,gt19_txusrclk_in,gt19_txusrclk2_in,gt19_txdata_in[31:0],gt19_gthtxn_out,gt19_gthtxp_out,gt19_txoutclk_out,gt19_txoutclkfabric_out,gt19_txoutclkpcs_out,gt19_txresetdone_out,gt19_txpolarity_in,gt19_txcharisk_in[3:0],GT0_QPLLOUTCLK_IN,GT0_QPLLOUTREFCLK_IN,GT1_QPLLOUTCLK_IN,GT1_QPLLOUTREFCLK_IN,GT2_QPLLOUTCLK_IN,GT2_QPLLOUTREFCLK_IN,GT3_QPLLOUTCLK_IN,GT3_QPLLOUTREFCLK_IN,GT4_QPLLOUTCLK_IN,GT4_QPLLOUTREFCLK_IN";
attribute x_core_info : string;
attribute x_core_info of stub : architecture is "gt625_fab20,gtwizard_v3_3,{protocol_file=Start_from_scratch}";
begin
end;
